import { SpeciesImpl } from 'io/github/sayakie/hakase/private/entity/SpeciesImpl.mjs'
import type { Comparable } from 'io/github/sayakie/hakase/util/Comparable.mjs'

export abstract class Species implements Comparable {
  public static readonly MissingNo = SpeciesImpl.of(0, 'MissingNo')
  public static readonly Bulbasaur = SpeciesImpl.of(1, 'Bulbasaur')
  public static readonly Ivysaur = SpeciesImpl.of(2, 'Ivysaur')
  public static readonly Venusaur = SpeciesImpl.of(3, 'Venusaur')
  public static readonly Charmander = SpeciesImpl.of(4, 'Charmander')
  public static readonly Charmeleon = SpeciesImpl.of(5, 'Charmeleon')
  public static readonly Charizard = SpeciesImpl.of(6, 'Charizard')
  public static readonly Squirtle = SpeciesImpl.of(7, 'Squirtle')
  public static readonly Wartortle = SpeciesImpl.of(8, 'Wartortle')
  public static readonly Blastoise = SpeciesImpl.of(9, 'Blastoise')
  public static readonly Caterpie = SpeciesImpl.of(10, 'Caterpie')
  public static readonly Metapod = SpeciesImpl.of(11, 'Metapod')
  public static readonly Butterfree = SpeciesImpl.of(12, 'Butterfree')
  public static readonly Weedle = SpeciesImpl.of(13, 'Weedle')
  public static readonly Kakuna = SpeciesImpl.of(14, 'Kakuna')
  public static readonly Beedrill = SpeciesImpl.of(15, 'Beedrill')
  public static readonly Pidgey = SpeciesImpl.of(16, 'Pidgey')
  public static readonly Pidgeotto = SpeciesImpl.of(17, 'Pidgeotto')
  public static readonly Pidgeot = SpeciesImpl.of(18, 'Pidgeot')
  public static readonly Rattata = SpeciesImpl.of(19, 'Rattata')
  public static readonly Raticate = SpeciesImpl.of(20, 'Raticate')
  public static readonly Spearow = SpeciesImpl.of(21, 'Spearow')
  public static readonly Fearow = SpeciesImpl.of(22, 'Fearow')
  public static readonly Ekans = SpeciesImpl.of(23, 'Ekans')
  public static readonly Arbok = SpeciesImpl.of(24, 'Arbok')
  public static readonly Pikachu = SpeciesImpl.of(25, 'Pikachu')
  public static readonly Raichu = SpeciesImpl.of(26, 'Raichu')
  public static readonly Sandshrew = SpeciesImpl.of(27, 'Sandshrew')
  public static readonly Sandslash = SpeciesImpl.of(28, 'Sandslash')
  public static readonly Nidoranfemale = SpeciesImpl.of(29, 'Nidoranfemale')
  public static readonly Nidorina = SpeciesImpl.of(30, 'Nidorina')
  public static readonly Nidoqueen = SpeciesImpl.of(31, 'Nidoqueen')
  public static readonly Nidoranmale = SpeciesImpl.of(32, 'Nidoranmale')
  public static readonly Nidorino = SpeciesImpl.of(33, 'Nidorino')
  public static readonly Nidoking = SpeciesImpl.of(34, 'Nidoking')
  public static readonly Clefairy = SpeciesImpl.of(35, 'Clefairy')
  public static readonly Clefable = SpeciesImpl.of(36, 'Clefable')
  public static readonly Vulpix = SpeciesImpl.of(37, 'Vulpix')
  public static readonly Ninetales = SpeciesImpl.of(38, 'Ninetales')
  public static readonly Jigglypuff = SpeciesImpl.of(39, 'Jigglypuff')
  public static readonly Wigglytuff = SpeciesImpl.of(40, 'Wigglytuff')
  public static readonly Zubat = SpeciesImpl.of(41, 'Zubat')
  public static readonly Golbat = SpeciesImpl.of(42, 'Golbat')
  public static readonly Oddish = SpeciesImpl.of(43, 'Oddish')
  public static readonly Gloom = SpeciesImpl.of(44, 'Gloom')
  public static readonly Vileplume = SpeciesImpl.of(45, 'Vileplume')
  public static readonly Paras = SpeciesImpl.of(46, 'Paras')
  public static readonly Parasect = SpeciesImpl.of(47, 'Parasect')
  public static readonly Venonat = SpeciesImpl.of(48, 'Venonat')
  public static readonly Venomoth = SpeciesImpl.of(49, 'Venomoth')
  public static readonly Diglett = SpeciesImpl.of(50, 'Diglett')
  public static readonly Dugtrio = SpeciesImpl.of(51, 'Dugtrio')
  public static readonly Meowth = SpeciesImpl.of(52, 'Meowth')
  public static readonly Persian = SpeciesImpl.of(53, 'Persian')
  public static readonly Psyduck = SpeciesImpl.of(54, 'Psyduck')
  public static readonly Golduck = SpeciesImpl.of(55, 'Golduck')
  public static readonly Mankey = SpeciesImpl.of(56, 'Mankey')
  public static readonly Primeape = SpeciesImpl.of(57, 'Primeape')
  public static readonly Growlithe = SpeciesImpl.of(58, 'Growlithe')
  public static readonly Arcanine = SpeciesImpl.of(59, 'Arcanine')
  public static readonly Poliwag = SpeciesImpl.of(60, 'Poliwag')
  public static readonly Poliwhirl = SpeciesImpl.of(61, 'Poliwhirl')
  public static readonly Poliwrath = SpeciesImpl.of(62, 'Poliwrath')
  public static readonly Abra = SpeciesImpl.of(63, 'Abra')
  public static readonly Kadabra = SpeciesImpl.of(64, 'Kadabra')
  public static readonly Alakazam = SpeciesImpl.of(65, 'Alakazam')
  public static readonly Machop = SpeciesImpl.of(66, 'Machop')
  public static readonly Machoke = SpeciesImpl.of(67, 'Machoke')
  public static readonly Machamp = SpeciesImpl.of(68, 'Machamp')
  public static readonly Bellsprout = SpeciesImpl.of(69, 'Bellsprout')
  public static readonly Weepinbell = SpeciesImpl.of(70, 'Weepinbell')
  public static readonly Victreebel = SpeciesImpl.of(71, 'Victreebel')
  public static readonly Tentacool = SpeciesImpl.of(72, 'Tentacool')
  public static readonly Tentacruel = SpeciesImpl.of(73, 'Tentacruel')
  public static readonly Geodude = SpeciesImpl.of(74, 'Geodude')
  public static readonly Graveler = SpeciesImpl.of(75, 'Graveler')
  public static readonly Golem = SpeciesImpl.of(76, 'Golem')
  public static readonly Ponyta = SpeciesImpl.of(77, 'Ponyta')
  public static readonly Rapidash = SpeciesImpl.of(78, 'Rapidash')
  public static readonly Slowpoke = SpeciesImpl.of(79, 'Slowpoke')
  public static readonly Slowbro = SpeciesImpl.of(80, 'Slowbro')
  public static readonly Magnemite = SpeciesImpl.of(81, 'Magnemite')
  public static readonly Magneton = SpeciesImpl.of(82, 'Magneton')
  public static readonly Farfetchd = SpeciesImpl.of(83, 'Farfetchd')
  public static readonly Doduo = SpeciesImpl.of(84, 'Doduo')
  public static readonly Dodrio = SpeciesImpl.of(85, 'Dodrio')
  public static readonly Seel = SpeciesImpl.of(86, 'Seel')
  public static readonly Dewgong = SpeciesImpl.of(87, 'Dewgong')
  public static readonly Grimer = SpeciesImpl.of(88, 'Grimer')
  public static readonly Muk = SpeciesImpl.of(89, 'Muk')
  public static readonly Shellder = SpeciesImpl.of(90, 'Shellder')
  public static readonly Cloyster = SpeciesImpl.of(91, 'Cloyster')
  public static readonly Gastly = SpeciesImpl.of(92, 'Gastly')
  public static readonly Haunter = SpeciesImpl.of(93, 'Haunter')
  public static readonly Gengar = SpeciesImpl.of(94, 'Gengar')
  public static readonly Onix = SpeciesImpl.of(95, 'Onix')
  public static readonly Drowzee = SpeciesImpl.of(96, 'Drowzee')
  public static readonly Hypno = SpeciesImpl.of(97, 'Hypno')
  public static readonly Krabby = SpeciesImpl.of(98, 'Krabby')
  public static readonly Kingler = SpeciesImpl.of(99, 'Kingler')
  public static readonly Voltorb = SpeciesImpl.of(100, 'Voltorb')
  public static readonly Electrode = SpeciesImpl.of(101, 'Electrode')
  public static readonly Exeggcute = SpeciesImpl.of(102, 'Exeggcute')
  public static readonly Exeggutor = SpeciesImpl.of(103, 'Exeggutor')
  public static readonly Cubone = SpeciesImpl.of(104, 'Cubone')
  public static readonly Marowak = SpeciesImpl.of(105, 'Marowak')
  public static readonly Hitmonlee = SpeciesImpl.of(106, 'Hitmonlee')
  public static readonly Hitmonchan = SpeciesImpl.of(107, 'Hitmonchan')
  public static readonly Lickitung = SpeciesImpl.of(108, 'Lickitung')
  public static readonly Koffing = SpeciesImpl.of(109, 'Koffing')
  public static readonly Weezing = SpeciesImpl.of(110, 'Weezing')
  public static readonly Rhyhorn = SpeciesImpl.of(111, 'Rhyhorn')
  public static readonly Rhydon = SpeciesImpl.of(112, 'Rhydon')
  public static readonly Chansey = SpeciesImpl.of(113, 'Chansey')
  public static readonly Tangela = SpeciesImpl.of(114, 'Tangela')
  public static readonly Kangaskhan = SpeciesImpl.of(115, 'Kangaskhan')
  public static readonly Horsea = SpeciesImpl.of(116, 'Horsea')
  public static readonly Seadra = SpeciesImpl.of(117, 'Seadra')
  public static readonly Goldeen = SpeciesImpl.of(118, 'Goldeen')
  public static readonly Seaking = SpeciesImpl.of(119, 'Seaking')
  public static readonly Staryu = SpeciesImpl.of(120, 'Staryu')
  public static readonly Starmie = SpeciesImpl.of(121, 'Starmie')
  public static readonly MrMime = SpeciesImpl.of(122, 'MrMime')
  public static readonly Scyther = SpeciesImpl.of(123, 'Scyther')
  public static readonly Jynx = SpeciesImpl.of(124, 'Jynx')
  public static readonly Electabuzz = SpeciesImpl.of(125, 'Electabuzz')
  public static readonly Magmar = SpeciesImpl.of(126, 'Magmar')
  public static readonly Pinsir = SpeciesImpl.of(127, 'Pinsir')
  public static readonly Tauros = SpeciesImpl.of(128, 'Tauros')
  public static readonly Magikarp = SpeciesImpl.of(129, 'Magikarp')
  public static readonly Gyarados = SpeciesImpl.of(130, 'Gyarados')
  public static readonly Lapras = SpeciesImpl.of(131, 'Lapras')
  public static readonly Ditto = SpeciesImpl.of(132, 'Ditto')
  public static readonly Eevee = SpeciesImpl.of(133, 'Eevee')
  public static readonly Vaporeon = SpeciesImpl.of(134, 'Vaporeon')
  public static readonly Jolteon = SpeciesImpl.of(135, 'Jolteon')
  public static readonly Flareon = SpeciesImpl.of(136, 'Flareon')
  public static readonly Porygon = SpeciesImpl.of(137, 'Porygon')
  public static readonly Omanyte = SpeciesImpl.of(138, 'Omanyte')
  public static readonly Omastar = SpeciesImpl.of(139, 'Omastar')
  public static readonly Kabuto = SpeciesImpl.of(140, 'Kabuto')
  public static readonly Kabutops = SpeciesImpl.of(141, 'Kabutops')
  public static readonly Aerodactyl = SpeciesImpl.of(142, 'Aerodactyl')
  public static readonly Snorlax = SpeciesImpl.of(143, 'Snorlax')
  public static readonly Articuno = SpeciesImpl.of(144, 'Articuno')
  public static readonly Zapdos = SpeciesImpl.of(145, 'Zapdos')
  public static readonly Moltres = SpeciesImpl.of(146, 'Moltres')
  public static readonly Dratini = SpeciesImpl.of(147, 'Dratini')
  public static readonly Dragonair = SpeciesImpl.of(148, 'Dragonair')
  public static readonly Dragonite = SpeciesImpl.of(149, 'Dragonite')
  public static readonly Mewtwo = SpeciesImpl.of(150, 'Mewtwo')
  public static readonly Mew = SpeciesImpl.of(151, 'Mew')
  public static readonly Chikorita = SpeciesImpl.of(152, 'Chikorita')
  public static readonly Bayleef = SpeciesImpl.of(153, 'Bayleef')
  public static readonly Meganium = SpeciesImpl.of(154, 'Meganium')
  public static readonly Cyndaquil = SpeciesImpl.of(155, 'Cyndaquil')
  public static readonly Quilava = SpeciesImpl.of(156, 'Quilava')
  public static readonly Typhlosion = SpeciesImpl.of(157, 'Typhlosion')
  public static readonly Totodile = SpeciesImpl.of(158, 'Totodile')
  public static readonly Croconaw = SpeciesImpl.of(159, 'Croconaw')
  public static readonly Feraligatr = SpeciesImpl.of(160, 'Feraligatr')
  public static readonly Sentret = SpeciesImpl.of(161, 'Sentret')
  public static readonly Furret = SpeciesImpl.of(162, 'Furret')
  public static readonly Hoothoot = SpeciesImpl.of(163, 'Hoothoot')
  public static readonly Noctowl = SpeciesImpl.of(164, 'Noctowl')
  public static readonly Ledyba = SpeciesImpl.of(165, 'Ledyba')
  public static readonly Ledian = SpeciesImpl.of(166, 'Ledian')
  public static readonly Spinarak = SpeciesImpl.of(167, 'Spinarak')
  public static readonly Ariados = SpeciesImpl.of(168, 'Ariados')
  public static readonly Crobat = SpeciesImpl.of(169, 'Crobat')
  public static readonly Chinchou = SpeciesImpl.of(170, 'Chinchou')
  public static readonly Lanturn = SpeciesImpl.of(171, 'Lanturn')
  public static readonly Pichu = SpeciesImpl.of(172, 'Pichu')
  public static readonly Cleffa = SpeciesImpl.of(173, 'Cleffa')
  public static readonly Igglybuff = SpeciesImpl.of(174, 'Igglybuff')
  public static readonly Togepi = SpeciesImpl.of(175, 'Togepi')
  public static readonly Togetic = SpeciesImpl.of(176, 'Togetic')
  public static readonly Natu = SpeciesImpl.of(177, 'Natu')
  public static readonly Xatu = SpeciesImpl.of(178, 'Xatu')
  public static readonly Mareep = SpeciesImpl.of(179, 'Mareep')
  public static readonly Flaaffy = SpeciesImpl.of(180, 'Flaaffy')
  public static readonly Ampharos = SpeciesImpl.of(181, 'Ampharos')
  public static readonly Bellossom = SpeciesImpl.of(182, 'Bellossom')
  public static readonly Marill = SpeciesImpl.of(183, 'Marill')
  public static readonly Azumarill = SpeciesImpl.of(184, 'Azumarill')
  public static readonly Sudowoodo = SpeciesImpl.of(185, 'Sudowoodo')
  public static readonly Politoed = SpeciesImpl.of(186, 'Politoed')
  public static readonly Hoppip = SpeciesImpl.of(187, 'Hoppip')
  public static readonly Skiploom = SpeciesImpl.of(188, 'Skiploom')
  public static readonly Jumpluff = SpeciesImpl.of(189, 'Jumpluff')
  public static readonly Aipom = SpeciesImpl.of(190, 'Aipom')
  public static readonly Sunkern = SpeciesImpl.of(191, 'Sunkern')
  public static readonly Sunflora = SpeciesImpl.of(192, 'Sunflora')
  public static readonly Yanma = SpeciesImpl.of(193, 'Yanma')
  public static readonly Wooper = SpeciesImpl.of(194, 'Wooper')
  public static readonly Quagsire = SpeciesImpl.of(195, 'Quagsire')
  public static readonly Espeon = SpeciesImpl.of(196, 'Espeon')
  public static readonly Umbreon = SpeciesImpl.of(197, 'Umbreon')
  public static readonly Murkrow = SpeciesImpl.of(198, 'Murkrow')
  public static readonly Slowking = SpeciesImpl.of(199, 'Slowking')
  public static readonly Misdreavus = SpeciesImpl.of(200, 'Misdreavus')
  public static readonly Unown = SpeciesImpl.of(201, 'Unown')
  public static readonly Wobbuffet = SpeciesImpl.of(202, 'Wobbuffet')
  public static readonly Girafarig = SpeciesImpl.of(203, 'Girafarig')
  public static readonly Pineco = SpeciesImpl.of(204, 'Pineco')
  public static readonly Forretress = SpeciesImpl.of(205, 'Forretress')
  public static readonly Dunsparce = SpeciesImpl.of(206, 'Dunsparce')
  public static readonly Gligar = SpeciesImpl.of(207, 'Gligar')
  public static readonly Steelix = SpeciesImpl.of(208, 'Steelix')
  public static readonly Snubbull = SpeciesImpl.of(209, 'Snubbull')
  public static readonly Granbull = SpeciesImpl.of(210, 'Granbull')
  public static readonly Qwilfish = SpeciesImpl.of(211, 'Qwilfish')
  public static readonly Scizor = SpeciesImpl.of(212, 'Scizor')
  public static readonly Shuckle = SpeciesImpl.of(213, 'Shuckle')
  public static readonly Heracross = SpeciesImpl.of(214, 'Heracross')
  public static readonly Sneasel = SpeciesImpl.of(215, 'Sneasel')
  public static readonly Teddiursa = SpeciesImpl.of(216, 'Teddiursa')
  public static readonly Ursaring = SpeciesImpl.of(217, 'Ursaring')
  public static readonly Slugma = SpeciesImpl.of(218, 'Slugma')
  public static readonly Magcargo = SpeciesImpl.of(219, 'Magcargo')
  public static readonly Swinub = SpeciesImpl.of(220, 'Swinub')
  public static readonly Piloswine = SpeciesImpl.of(221, 'Piloswine')
  public static readonly Corsola = SpeciesImpl.of(222, 'Corsola')
  public static readonly Remoraid = SpeciesImpl.of(223, 'Remoraid')
  public static readonly Octillery = SpeciesImpl.of(224, 'Octillery')
  public static readonly Delibird = SpeciesImpl.of(225, 'Delibird')
  public static readonly Mantine = SpeciesImpl.of(226, 'Mantine')
  public static readonly Skarmory = SpeciesImpl.of(227, 'Skarmory')
  public static readonly Houndour = SpeciesImpl.of(228, 'Houndour')
  public static readonly Houndoom = SpeciesImpl.of(229, 'Houndoom')
  public static readonly Kingdra = SpeciesImpl.of(230, 'Kingdra')
  public static readonly Phanpy = SpeciesImpl.of(231, 'Phanpy')
  public static readonly Donphan = SpeciesImpl.of(232, 'Donphan')
  public static readonly Porygon2 = SpeciesImpl.of(233, 'Porygon2')
  public static readonly Stantler = SpeciesImpl.of(234, 'Stantler')
  public static readonly Smeargle = SpeciesImpl.of(235, 'Smeargle')
  public static readonly Tyrogue = SpeciesImpl.of(236, 'Tyrogue')
  public static readonly Hitmontop = SpeciesImpl.of(237, 'Hitmontop')
  public static readonly Smoochum = SpeciesImpl.of(238, 'Smoochum')
  public static readonly Elekid = SpeciesImpl.of(239, 'Elekid')
  public static readonly Magby = SpeciesImpl.of(240, 'Magby')
  public static readonly Miltank = SpeciesImpl.of(241, 'Miltank')
  public static readonly Blissey = SpeciesImpl.of(242, 'Blissey')
  public static readonly Raikou = SpeciesImpl.of(243, 'Raikou')
  public static readonly Entei = SpeciesImpl.of(244, 'Entei')
  public static readonly Suicune = SpeciesImpl.of(245, 'Suicune')
  public static readonly Larvitar = SpeciesImpl.of(246, 'Larvitar')
  public static readonly Pupitar = SpeciesImpl.of(247, 'Pupitar')
  public static readonly Tyranitar = SpeciesImpl.of(248, 'Tyranitar')
  public static readonly Lugia = SpeciesImpl.of(249, 'Lugia')
  public static readonly Hooh = SpeciesImpl.of(250, 'Ho-Oh')
  public static readonly Celebi = SpeciesImpl.of(251, 'Celebi')
  public static readonly Treecko = SpeciesImpl.of(252, 'Treecko')
  public static readonly Grovyle = SpeciesImpl.of(253, 'Grovyle')
  public static readonly Sceptile = SpeciesImpl.of(254, 'Sceptile')
  public static readonly Torchic = SpeciesImpl.of(255, 'Torchic')
  public static readonly Combusken = SpeciesImpl.of(256, 'Combusken')
  public static readonly Blaziken = SpeciesImpl.of(257, 'Blaziken')
  public static readonly Mudkip = SpeciesImpl.of(258, 'Mudkip')
  public static readonly Marshtomp = SpeciesImpl.of(259, 'Marshtomp')
  public static readonly Swampert = SpeciesImpl.of(260, 'Swampert')
  public static readonly Poochyena = SpeciesImpl.of(261, 'Poochyena')
  public static readonly Mightyena = SpeciesImpl.of(262, 'Mightyena')
  public static readonly Zigzagoon = SpeciesImpl.of(263, 'Zigzagoon')
  public static readonly Linoone = SpeciesImpl.of(264, 'Linoone')
  public static readonly Wurmple = SpeciesImpl.of(265, 'Wurmple')
  public static readonly Silcoon = SpeciesImpl.of(266, 'Silcoon')
  public static readonly Beautifly = SpeciesImpl.of(267, 'Beautifly')
  public static readonly Cascoon = SpeciesImpl.of(268, 'Cascoon')
  public static readonly Dustox = SpeciesImpl.of(269, 'Dustox')
  public static readonly Lotad = SpeciesImpl.of(270, 'Lotad')
  public static readonly Lombre = SpeciesImpl.of(271, 'Lombre')
  public static readonly Ludicolo = SpeciesImpl.of(272, 'Ludicolo')
  public static readonly Seedot = SpeciesImpl.of(273, 'Seedot')
  public static readonly Nuzleaf = SpeciesImpl.of(274, 'Nuzleaf')
  public static readonly Shiftry = SpeciesImpl.of(275, 'Shiftry')
  public static readonly Taillow = SpeciesImpl.of(276, 'Taillow')
  public static readonly Swellow = SpeciesImpl.of(277, 'Swellow')
  public static readonly Wingull = SpeciesImpl.of(278, 'Wingull')
  public static readonly Pelipper = SpeciesImpl.of(279, 'Pelipper')
  public static readonly Ralts = SpeciesImpl.of(280, 'Ralts')
  public static readonly Kirlia = SpeciesImpl.of(281, 'Kirlia')
  public static readonly Gardevoir = SpeciesImpl.of(282, 'Gardevoir')
  public static readonly Surskit = SpeciesImpl.of(283, 'Surskit')
  public static readonly Masquerain = SpeciesImpl.of(284, 'Masquerain')
  public static readonly Shroomish = SpeciesImpl.of(285, 'Shroomish')
  public static readonly Breloom = SpeciesImpl.of(286, 'Breloom')
  public static readonly Slakoth = SpeciesImpl.of(287, 'Slakoth')
  public static readonly Vigoroth = SpeciesImpl.of(288, 'Vigoroth')
  public static readonly Slaking = SpeciesImpl.of(289, 'Slaking')
  public static readonly Nincada = SpeciesImpl.of(290, 'Nincada')
  public static readonly Ninjask = SpeciesImpl.of(291, 'Ninjask')
  public static readonly Shedinja = SpeciesImpl.of(292, 'Shedinja')
  public static readonly Whismur = SpeciesImpl.of(293, 'Whismur')
  public static readonly Loudred = SpeciesImpl.of(294, 'Loudred')
  public static readonly Exploud = SpeciesImpl.of(295, 'Exploud')
  public static readonly Makuhita = SpeciesImpl.of(296, 'Makuhita')
  public static readonly Hariyama = SpeciesImpl.of(297, 'Hariyama')
  public static readonly Azurill = SpeciesImpl.of(298, 'Azurill')
  public static readonly Nosepass = SpeciesImpl.of(299, 'Nosepass')
  public static readonly Skitty = SpeciesImpl.of(300, 'Skitty')
  public static readonly Delcatty = SpeciesImpl.of(301, 'Delcatty')
  public static readonly Sableye = SpeciesImpl.of(302, 'Sableye')
  public static readonly Mawile = SpeciesImpl.of(303, 'Mawile')
  public static readonly Aron = SpeciesImpl.of(304, 'Aron')
  public static readonly Lairon = SpeciesImpl.of(305, 'Lairon')
  public static readonly Aggron = SpeciesImpl.of(306, 'Aggron')
  public static readonly Meditite = SpeciesImpl.of(307, 'Meditite')
  public static readonly Medicham = SpeciesImpl.of(308, 'Medicham')
  public static readonly Electrike = SpeciesImpl.of(309, 'Electrike')
  public static readonly Manectric = SpeciesImpl.of(310, 'Manectric')
  public static readonly Plusle = SpeciesImpl.of(311, 'Plusle')
  public static readonly Minun = SpeciesImpl.of(312, 'Minun')
  public static readonly Volbeat = SpeciesImpl.of(313, 'Volbeat')
  public static readonly Illumise = SpeciesImpl.of(314, 'Illumise')
  public static readonly Roselia = SpeciesImpl.of(315, 'Roselia')
  public static readonly Gulpin = SpeciesImpl.of(316, 'Gulpin')
  public static readonly Swalot = SpeciesImpl.of(317, 'Swalot')
  public static readonly Carvanha = SpeciesImpl.of(318, 'Carvanha')
  public static readonly Sharpedo = SpeciesImpl.of(319, 'Sharpedo')
  public static readonly Wailmer = SpeciesImpl.of(320, 'Wailmer')
  public static readonly Wailord = SpeciesImpl.of(321, 'Wailord')
  public static readonly Numel = SpeciesImpl.of(322, 'Numel')
  public static readonly Camerupt = SpeciesImpl.of(323, 'Camerupt')
  public static readonly Torkoal = SpeciesImpl.of(324, 'Torkoal')
  public static readonly Spoink = SpeciesImpl.of(325, 'Spoink')
  public static readonly Grumpig = SpeciesImpl.of(326, 'Grumpig')
  public static readonly Spinda = SpeciesImpl.of(327, 'Spinda')
  public static readonly Trapinch = SpeciesImpl.of(328, 'Trapinch')
  public static readonly Vibrava = SpeciesImpl.of(329, 'Vibrava')
  public static readonly Flygon = SpeciesImpl.of(330, 'Flygon')
  public static readonly Cacnea = SpeciesImpl.of(331, 'Cacnea')
  public static readonly Cacturne = SpeciesImpl.of(332, 'Cacturne')
  public static readonly Swablu = SpeciesImpl.of(333, 'Swablu')
  public static readonly Altaria = SpeciesImpl.of(334, 'Altaria')
  public static readonly Zangoose = SpeciesImpl.of(335, 'Zangoose')
  public static readonly Seviper = SpeciesImpl.of(336, 'Seviper')
  public static readonly Lunatone = SpeciesImpl.of(337, 'Lunatone')
  public static readonly Solrock = SpeciesImpl.of(338, 'Solrock')
  public static readonly Barboach = SpeciesImpl.of(339, 'Barboach')
  public static readonly Whiscash = SpeciesImpl.of(340, 'Whiscash')
  public static readonly Corphish = SpeciesImpl.of(341, 'Corphish')
  public static readonly Crawdaunt = SpeciesImpl.of(342, 'Crawdaunt')
  public static readonly Baltoy = SpeciesImpl.of(343, 'Baltoy')
  public static readonly Claydol = SpeciesImpl.of(344, 'Claydol')
  public static readonly Lileep = SpeciesImpl.of(345, 'Lileep')
  public static readonly Cradily = SpeciesImpl.of(346, 'Cradily')
  public static readonly Anorith = SpeciesImpl.of(347, 'Anorith')
  public static readonly Armaldo = SpeciesImpl.of(348, 'Armaldo')
  public static readonly Feebas = SpeciesImpl.of(349, 'Feebas')
  public static readonly Milotic = SpeciesImpl.of(350, 'Milotic')
  public static readonly Castform = SpeciesImpl.of(351, 'Castform')
  public static readonly Kecleon = SpeciesImpl.of(352, 'Kecleon')
  public static readonly Shuppet = SpeciesImpl.of(353, 'Shuppet')
  public static readonly Banette = SpeciesImpl.of(354, 'Banette')
  public static readonly Duskull = SpeciesImpl.of(355, 'Duskull')
  public static readonly Dusclops = SpeciesImpl.of(356, 'Dusclops')
  public static readonly Tropius = SpeciesImpl.of(357, 'Tropius')
  public static readonly Chimecho = SpeciesImpl.of(358, 'Chimecho')
  public static readonly Absol = SpeciesImpl.of(359, 'Absol')
  public static readonly Wynaut = SpeciesImpl.of(360, 'Wynaut')
  public static readonly Snorunt = SpeciesImpl.of(361, 'Snorunt')
  public static readonly Glalie = SpeciesImpl.of(362, 'Glalie')
  public static readonly Spheal = SpeciesImpl.of(363, 'Spheal')
  public static readonly Sealeo = SpeciesImpl.of(364, 'Sealeo')
  public static readonly Walrein = SpeciesImpl.of(365, 'Walrein')
  public static readonly Clamperl = SpeciesImpl.of(366, 'Clamperl')
  public static readonly Huntail = SpeciesImpl.of(367, 'Huntail')
  public static readonly Gorebyss = SpeciesImpl.of(368, 'Gorebyss')
  public static readonly Relicanth = SpeciesImpl.of(369, 'Relicanth')
  public static readonly Luvdisc = SpeciesImpl.of(370, 'Luvdisc')
  public static readonly Bagon = SpeciesImpl.of(371, 'Bagon')
  public static readonly Shelgon = SpeciesImpl.of(372, 'Shelgon')
  public static readonly Salamence = SpeciesImpl.of(373, 'Salamence')
  public static readonly Beldum = SpeciesImpl.of(374, 'Beldum')
  public static readonly Metang = SpeciesImpl.of(375, 'Metang')
  public static readonly Metagross = SpeciesImpl.of(376, 'Metagross')
  public static readonly Regirock = SpeciesImpl.of(377, 'Regirock')
  public static readonly Regice = SpeciesImpl.of(378, 'Regice')
  public static readonly Registeel = SpeciesImpl.of(379, 'Registeel')
  public static readonly Latias = SpeciesImpl.of(380, 'Latias')
  public static readonly Latios = SpeciesImpl.of(381, 'Latios')
  public static readonly Kyogre = SpeciesImpl.of(382, 'Kyogre')
  public static readonly Groudon = SpeciesImpl.of(383, 'Groudon')
  public static readonly Rayquaza = SpeciesImpl.of(384, 'Rayquaza')
  public static readonly Jirachi = SpeciesImpl.of(385, 'Jirachi')
  public static readonly Deoxys = SpeciesImpl.of(386, 'Deoxys')
  public static readonly Turtwig = SpeciesImpl.of(387, 'Turtwig')
  public static readonly Grotle = SpeciesImpl.of(388, 'Grotle')
  public static readonly Torterra = SpeciesImpl.of(389, 'Torterra')
  public static readonly Chimchar = SpeciesImpl.of(390, 'Chimchar')
  public static readonly Monferno = SpeciesImpl.of(391, 'Monferno')
  public static readonly Infernape = SpeciesImpl.of(392, 'Infernape')
  public static readonly Piplup = SpeciesImpl.of(393, 'Piplup')
  public static readonly Prinplup = SpeciesImpl.of(394, 'Prinplup')
  public static readonly Empoleon = SpeciesImpl.of(395, 'Empoleon')
  public static readonly Starly = SpeciesImpl.of(396, 'Starly')
  public static readonly Staravia = SpeciesImpl.of(397, 'Staravia')
  public static readonly Staraptor = SpeciesImpl.of(398, 'Staraptor')
  public static readonly Bidoof = SpeciesImpl.of(399, 'Bidoof')
  public static readonly Bibarel = SpeciesImpl.of(400, 'Bibarel')
  public static readonly Kricketot = SpeciesImpl.of(401, 'Kricketot')
  public static readonly Kricketune = SpeciesImpl.of(402, 'Kricketune')
  public static readonly Shinx = SpeciesImpl.of(403, 'Shinx')
  public static readonly Luxio = SpeciesImpl.of(404, 'Luxio')
  public static readonly Luxray = SpeciesImpl.of(405, 'Luxray')
  public static readonly Budew = SpeciesImpl.of(406, 'Budew')
  public static readonly Roserade = SpeciesImpl.of(407, 'Roserade')
  public static readonly Cranidos = SpeciesImpl.of(408, 'Cranidos')
  public static readonly Rampardos = SpeciesImpl.of(409, 'Rampardos')
  public static readonly Shieldon = SpeciesImpl.of(410, 'Shieldon')
  public static readonly Bastiodon = SpeciesImpl.of(411, 'Bastiodon')
  public static readonly Burmy = SpeciesImpl.of(412, 'Burmy')
  public static readonly Wormadam = SpeciesImpl.of(413, 'Wormadam')
  public static readonly Mothim = SpeciesImpl.of(414, 'Mothim')
  public static readonly Combee = SpeciesImpl.of(415, 'Combee')
  public static readonly Vespiquen = SpeciesImpl.of(416, 'Vespiquen')
  public static readonly Pachirisu = SpeciesImpl.of(417, 'Pachirisu')
  public static readonly Buizel = SpeciesImpl.of(418, 'Buizel')
  public static readonly Floatzel = SpeciesImpl.of(419, 'Floatzel')
  public static readonly Cherubi = SpeciesImpl.of(420, 'Cherubi')
  public static readonly Cherrim = SpeciesImpl.of(421, 'Cherrim')
  public static readonly Shellos = SpeciesImpl.of(422, 'Shellos')
  public static readonly Gastrodon = SpeciesImpl.of(423, 'Gastrodon')
  public static readonly Ambipom = SpeciesImpl.of(424, 'Ambipom')
  public static readonly Drifloon = SpeciesImpl.of(425, 'Drifloon')
  public static readonly Drifblim = SpeciesImpl.of(426, 'Drifblim')
  public static readonly Buneary = SpeciesImpl.of(427, 'Buneary')
  public static readonly Lopunny = SpeciesImpl.of(428, 'Lopunny')
  public static readonly Mismagius = SpeciesImpl.of(429, 'Mismagius')
  public static readonly Honchkrow = SpeciesImpl.of(430, 'Honchkrow')
  public static readonly Glameow = SpeciesImpl.of(431, 'Glameow')
  public static readonly Purugly = SpeciesImpl.of(432, 'Purugly')
  public static readonly Chingling = SpeciesImpl.of(433, 'Chingling')
  public static readonly Stunky = SpeciesImpl.of(434, 'Stunky')
  public static readonly Skuntank = SpeciesImpl.of(435, 'Skuntank')
  public static readonly Bronzor = SpeciesImpl.of(436, 'Bronzor')
  public static readonly Bronzong = SpeciesImpl.of(437, 'Bronzong')
  public static readonly Bonsly = SpeciesImpl.of(438, 'Bonsly')
  public static readonly MimeJr = SpeciesImpl.of(439, 'MimeJr')
  public static readonly Happiny = SpeciesImpl.of(440, 'Happiny')
  public static readonly Chatot = SpeciesImpl.of(441, 'Chatot')
  public static readonly Spiritomb = SpeciesImpl.of(442, 'Spiritomb')
  public static readonly Gible = SpeciesImpl.of(443, 'Gible')
  public static readonly Gabite = SpeciesImpl.of(444, 'Gabite')
  public static readonly Garchomp = SpeciesImpl.of(445, 'Garchomp')
  public static readonly Munchlax = SpeciesImpl.of(446, 'Munchlax')
  public static readonly Riolu = SpeciesImpl.of(447, 'Riolu')
  public static readonly Lucario = SpeciesImpl.of(448, 'Lucario')
  public static readonly Hippopotas = SpeciesImpl.of(449, 'Hippopotas')
  public static readonly Hippowdon = SpeciesImpl.of(450, 'Hippowdon')
  public static readonly Skorupi = SpeciesImpl.of(451, 'Skorupi')
  public static readonly Drapion = SpeciesImpl.of(452, 'Drapion')
  public static readonly Croagunk = SpeciesImpl.of(453, 'Croagunk')
  public static readonly Toxicroak = SpeciesImpl.of(454, 'Toxicroak')
  public static readonly Carnivine = SpeciesImpl.of(455, 'Carnivine')
  public static readonly Finneon = SpeciesImpl.of(456, 'Finneon')
  public static readonly Lumineon = SpeciesImpl.of(457, 'Lumineon')
  public static readonly Mantyke = SpeciesImpl.of(458, 'Mantyke')
  public static readonly Snover = SpeciesImpl.of(459, 'Snover')
  public static readonly Abomasnow = SpeciesImpl.of(460, 'Abomasnow')
  public static readonly Weavile = SpeciesImpl.of(461, 'Weavile')
  public static readonly Magnezone = SpeciesImpl.of(462, 'Magnezone')
  public static readonly Lickilicky = SpeciesImpl.of(463, 'Lickilicky')
  public static readonly Rhyperior = SpeciesImpl.of(464, 'Rhyperior')
  public static readonly Tangrowth = SpeciesImpl.of(465, 'Tangrowth')
  public static readonly Electivire = SpeciesImpl.of(466, 'Electivire')
  public static readonly Magmortar = SpeciesImpl.of(467, 'Magmortar')
  public static readonly Togekiss = SpeciesImpl.of(468, 'Togekiss')
  public static readonly Yanmega = SpeciesImpl.of(469, 'Yanmega')
  public static readonly Leafeon = SpeciesImpl.of(470, 'Leafeon')
  public static readonly Glaceon = SpeciesImpl.of(471, 'Glaceon')
  public static readonly Gliscor = SpeciesImpl.of(472, 'Gliscor')
  public static readonly Mamoswine = SpeciesImpl.of(473, 'Mamoswine')
  public static readonly PorygonZ = SpeciesImpl.of(474, 'Porygon-Z')
  public static readonly Gallade = SpeciesImpl.of(475, 'Gallade')
  public static readonly Probopass = SpeciesImpl.of(476, 'Probopass')
  public static readonly Dusknoir = SpeciesImpl.of(477, 'Dusknoir')
  public static readonly Froslass = SpeciesImpl.of(478, 'Froslass')
  public static readonly Rotom = SpeciesImpl.of(479, 'Rotom')
  public static readonly Uxie = SpeciesImpl.of(480, 'Uxie')
  public static readonly Mesprit = SpeciesImpl.of(481, 'Mesprit')
  public static readonly Azelf = SpeciesImpl.of(482, 'Azelf')
  public static readonly Dialga = SpeciesImpl.of(483, 'Dialga')
  public static readonly Palkia = SpeciesImpl.of(484, 'Palkia')
  public static readonly Heatran = SpeciesImpl.of(485, 'Heatran')
  public static readonly Regigigas = SpeciesImpl.of(486, 'Regigigas')
  public static readonly Giratina = SpeciesImpl.of(487, 'Giratina')
  public static readonly Cresselia = SpeciesImpl.of(488, 'Cresselia')
  public static readonly Phione = SpeciesImpl.of(489, 'Phione')
  public static readonly Manaphy = SpeciesImpl.of(490, 'Manaphy')
  public static readonly Darkrai = SpeciesImpl.of(491, 'Darkrai')
  public static readonly Shaymin = SpeciesImpl.of(492, 'Shaymin')
  public static readonly Arceus = SpeciesImpl.of(493, 'Arceus')
  public static readonly Victini = SpeciesImpl.of(494, 'Victini')
  public static readonly Snivy = SpeciesImpl.of(495, 'Snivy')
  public static readonly Servine = SpeciesImpl.of(496, 'Servine')
  public static readonly Serperior = SpeciesImpl.of(497, 'Serperior')
  public static readonly Tepig = SpeciesImpl.of(498, 'Tepig')
  public static readonly Pignite = SpeciesImpl.of(499, 'Pignite')
  public static readonly Emboar = SpeciesImpl.of(500, 'Emboar')
  public static readonly Oshawott = SpeciesImpl.of(501, 'Oshawott')
  public static readonly Dewott = SpeciesImpl.of(502, 'Dewott')
  public static readonly Samurott = SpeciesImpl.of(503, 'Samurott')
  public static readonly Patrat = SpeciesImpl.of(504, 'Patrat')
  public static readonly Watchog = SpeciesImpl.of(505, 'Watchog')
  public static readonly Lillipup = SpeciesImpl.of(506, 'Lillipup')
  public static readonly Herdier = SpeciesImpl.of(507, 'Herdier')
  public static readonly Stoutland = SpeciesImpl.of(508, 'Stoutland')
  public static readonly Purrloin = SpeciesImpl.of(509, 'Purrloin')
  public static readonly Liepard = SpeciesImpl.of(510, 'Liepard')
  public static readonly Pansage = SpeciesImpl.of(511, 'Pansage')
  public static readonly Simisage = SpeciesImpl.of(512, 'Simisage')
  public static readonly Pansear = SpeciesImpl.of(513, 'Pansear')
  public static readonly Simisear = SpeciesImpl.of(514, 'Simisear')
  public static readonly Panpour = SpeciesImpl.of(515, 'Panpour')
  public static readonly Simipour = SpeciesImpl.of(516, 'Simipour')
  public static readonly Munna = SpeciesImpl.of(517, 'Munna')
  public static readonly Musharna = SpeciesImpl.of(518, 'Musharna')
  public static readonly Pidove = SpeciesImpl.of(519, 'Pidove')
  public static readonly Tranquill = SpeciesImpl.of(520, 'Tranquill')
  public static readonly Unfezant = SpeciesImpl.of(521, 'Unfezant')
  public static readonly Blitzle = SpeciesImpl.of(522, 'Blitzle')
  public static readonly Zebstrika = SpeciesImpl.of(523, 'Zebstrika')
  public static readonly Roggenrola = SpeciesImpl.of(524, 'Roggenrola')
  public static readonly Boldore = SpeciesImpl.of(525, 'Boldore')
  public static readonly Gigalith = SpeciesImpl.of(526, 'Gigalith')
  public static readonly Woobat = SpeciesImpl.of(527, 'Woobat')
  public static readonly Swoobat = SpeciesImpl.of(528, 'Swoobat')
  public static readonly Drilbur = SpeciesImpl.of(529, 'Drilbur')
  public static readonly Excadrill = SpeciesImpl.of(530, 'Excadrill')
  public static readonly Audino = SpeciesImpl.of(531, 'Audino')
  public static readonly Timburr = SpeciesImpl.of(532, 'Timburr')
  public static readonly Gurdurr = SpeciesImpl.of(533, 'Gurdurr')
  public static readonly Conkeldurr = SpeciesImpl.of(534, 'Conkeldurr')
  public static readonly Tympole = SpeciesImpl.of(535, 'Tympole')
  public static readonly Palpitoad = SpeciesImpl.of(536, 'Palpitoad')
  public static readonly Seismitoad = SpeciesImpl.of(537, 'Seismitoad')
  public static readonly Throh = SpeciesImpl.of(538, 'Throh')
  public static readonly Sawk = SpeciesImpl.of(539, 'Sawk')
  public static readonly Sewaddle = SpeciesImpl.of(540, 'Sewaddle')
  public static readonly Swadloon = SpeciesImpl.of(541, 'Swadloon')
  public static readonly Leavanny = SpeciesImpl.of(542, 'Leavanny')
  public static readonly Venipede = SpeciesImpl.of(543, 'Venipede')
  public static readonly Whirlipede = SpeciesImpl.of(544, 'Whirlipede')
  public static readonly Scolipede = SpeciesImpl.of(545, 'Scolipede')
  public static readonly Cottonee = SpeciesImpl.of(546, 'Cottonee')
  public static readonly Whimsicott = SpeciesImpl.of(547, 'Whimsicott')
  public static readonly Petilil = SpeciesImpl.of(548, 'Petilil')
  public static readonly Lilligant = SpeciesImpl.of(549, 'Lilligant')
  public static readonly Basculin = SpeciesImpl.of(550, 'Basculin')
  public static readonly Sandile = SpeciesImpl.of(551, 'Sandile')
  public static readonly Krokorok = SpeciesImpl.of(552, 'Krokorok')
  public static readonly Krookodile = SpeciesImpl.of(553, 'Krookodile')
  public static readonly Darumaka = SpeciesImpl.of(554, 'Darumaka')
  public static readonly Darmanitan = SpeciesImpl.of(555, 'Darmanitan')
  public static readonly Maractus = SpeciesImpl.of(556, 'Maractus')
  public static readonly Dwebble = SpeciesImpl.of(557, 'Dwebble')
  public static readonly Crustle = SpeciesImpl.of(558, 'Crustle')
  public static readonly Scraggy = SpeciesImpl.of(559, 'Scraggy')
  public static readonly Scrafty = SpeciesImpl.of(560, 'Scrafty')
  public static readonly Sigilyph = SpeciesImpl.of(561, 'Sigilyph')
  public static readonly Yamask = SpeciesImpl.of(562, 'Yamask')
  public static readonly Cofagrigus = SpeciesImpl.of(563, 'Cofagrigus')
  public static readonly Tirtouga = SpeciesImpl.of(564, 'Tirtouga')
  public static readonly Carracosta = SpeciesImpl.of(565, 'Carracosta')
  public static readonly Archen = SpeciesImpl.of(566, 'Archen')
  public static readonly Archeops = SpeciesImpl.of(567, 'Archeops')
  public static readonly Trubbish = SpeciesImpl.of(568, 'Trubbish')
  public static readonly Garbodor = SpeciesImpl.of(569, 'Garbodor')
  public static readonly Zorua = SpeciesImpl.of(570, 'Zorua')
  public static readonly Zoroark = SpeciesImpl.of(571, 'Zoroark')
  public static readonly Minccino = SpeciesImpl.of(572, 'Minccino')
  public static readonly Cinccino = SpeciesImpl.of(573, 'Cinccino')
  public static readonly Gothita = SpeciesImpl.of(574, 'Gothita')
  public static readonly Gothorita = SpeciesImpl.of(575, 'Gothorita')
  public static readonly Gothitelle = SpeciesImpl.of(576, 'Gothitelle')
  public static readonly Solosis = SpeciesImpl.of(577, 'Solosis')
  public static readonly Duosion = SpeciesImpl.of(578, 'Duosion')
  public static readonly Reuniclus = SpeciesImpl.of(579, 'Reuniclus')
  public static readonly Ducklett = SpeciesImpl.of(580, 'Ducklett')
  public static readonly Swanna = SpeciesImpl.of(581, 'Swanna')
  public static readonly Vanillite = SpeciesImpl.of(582, 'Vanillite')
  public static readonly Vanillish = SpeciesImpl.of(583, 'Vanillish')
  public static readonly Vanilluxe = SpeciesImpl.of(584, 'Vanilluxe')
  public static readonly Deerling = SpeciesImpl.of(585, 'Deerling')
  public static readonly Sawsbuck = SpeciesImpl.of(586, 'Sawsbuck')
  public static readonly Emolga = SpeciesImpl.of(587, 'Emolga')
  public static readonly Karrablast = SpeciesImpl.of(588, 'Karrablast')
  public static readonly Escavalier = SpeciesImpl.of(589, 'Escavalier')
  public static readonly Foongus = SpeciesImpl.of(590, 'Foongus')
  public static readonly Amoonguss = SpeciesImpl.of(591, 'Amoonguss')
  public static readonly Frillish = SpeciesImpl.of(592, 'Frillish')
  public static readonly Jellicent = SpeciesImpl.of(593, 'Jellicent')
  public static readonly Alomomola = SpeciesImpl.of(594, 'Alomomola')
  public static readonly Joltik = SpeciesImpl.of(595, 'Joltik')
  public static readonly Galvantula = SpeciesImpl.of(596, 'Galvantula')
  public static readonly Ferroseed = SpeciesImpl.of(597, 'Ferroseed')
  public static readonly Ferrothorn = SpeciesImpl.of(598, 'Ferrothorn')
  public static readonly Klink = SpeciesImpl.of(599, 'Klink')
  public static readonly Klang = SpeciesImpl.of(600, 'Klang')
  public static readonly Klinklang = SpeciesImpl.of(601, 'Klinklang')
  public static readonly Tynamo = SpeciesImpl.of(602, 'Tynamo')
  public static readonly Eelektrik = SpeciesImpl.of(603, 'Eelektrik')
  public static readonly Eelektross = SpeciesImpl.of(604, 'Eelektross')
  public static readonly Elgyem = SpeciesImpl.of(605, 'Elgyem')
  public static readonly Beheeyem = SpeciesImpl.of(606, 'Beheeyem')
  public static readonly Litwick = SpeciesImpl.of(607, 'Litwick')
  public static readonly Lampent = SpeciesImpl.of(608, 'Lampent')
  public static readonly Chandelure = SpeciesImpl.of(609, 'Chandelure')
  public static readonly Axew = SpeciesImpl.of(610, 'Axew')
  public static readonly Fraxure = SpeciesImpl.of(611, 'Fraxure')
  public static readonly Haxorus = SpeciesImpl.of(612, 'Haxorus')
  public static readonly Cubchoo = SpeciesImpl.of(613, 'Cubchoo')
  public static readonly Beartic = SpeciesImpl.of(614, 'Beartic')
  public static readonly Cryogonal = SpeciesImpl.of(615, 'Cryogonal')
  public static readonly Shelmet = SpeciesImpl.of(616, 'Shelmet')
  public static readonly Accelgor = SpeciesImpl.of(617, 'Accelgor')
  public static readonly Stunfisk = SpeciesImpl.of(618, 'Stunfisk')
  public static readonly Mienfoo = SpeciesImpl.of(619, 'Mienfoo')
  public static readonly Mienshao = SpeciesImpl.of(620, 'Mienshao')
  public static readonly Druddigon = SpeciesImpl.of(621, 'Druddigon')
  public static readonly Golett = SpeciesImpl.of(622, 'Golett')
  public static readonly Golurk = SpeciesImpl.of(623, 'Golurk')
  public static readonly Pawniard = SpeciesImpl.of(624, 'Pawniard')
  public static readonly Bisharp = SpeciesImpl.of(625, 'Bisharp')
  public static readonly Bouffalant = SpeciesImpl.of(626, 'Bouffalant')
  public static readonly Rufflet = SpeciesImpl.of(627, 'Rufflet')
  public static readonly Braviary = SpeciesImpl.of(628, 'Braviary')
  public static readonly Vullaby = SpeciesImpl.of(629, 'Vullaby')
  public static readonly Mandibuzz = SpeciesImpl.of(630, 'Mandibuzz')
  public static readonly Heatmor = SpeciesImpl.of(631, 'Heatmor')
  public static readonly Durant = SpeciesImpl.of(632, 'Durant')
  public static readonly Deino = SpeciesImpl.of(633, 'Deino')
  public static readonly Zweilous = SpeciesImpl.of(634, 'Zweilous')
  public static readonly Hydreigon = SpeciesImpl.of(635, 'Hydreigon')
  public static readonly Larvesta = SpeciesImpl.of(636, 'Larvesta')
  public static readonly Volcarona = SpeciesImpl.of(637, 'Volcarona')
  public static readonly Cobalion = SpeciesImpl.of(638, 'Cobalion')
  public static readonly Terrakion = SpeciesImpl.of(639, 'Terrakion')
  public static readonly Virizion = SpeciesImpl.of(640, 'Virizion')
  public static readonly Tornadus = SpeciesImpl.of(641, 'Tornadus')
  public static readonly Thundurus = SpeciesImpl.of(642, 'Thundurus')
  public static readonly Reshiram = SpeciesImpl.of(643, 'Reshiram')
  public static readonly Zekrom = SpeciesImpl.of(644, 'Zekrom')
  public static readonly Landorus = SpeciesImpl.of(645, 'Landorus')
  public static readonly Kyurem = SpeciesImpl.of(646, 'Kyurem')
  public static readonly Keldeo = SpeciesImpl.of(647, 'Keldeo')
  public static readonly Meloetta = SpeciesImpl.of(648, 'Meloetta')
  public static readonly Genesect = SpeciesImpl.of(649, 'Genesect')
  public static readonly Chespin = SpeciesImpl.of(650, 'Chespin')
  public static readonly Quilladin = SpeciesImpl.of(651, 'Quilladin')
  public static readonly Chesnaught = SpeciesImpl.of(652, 'Chesnaught')
  public static readonly Fennekin = SpeciesImpl.of(653, 'Fennekin')
  public static readonly Braixen = SpeciesImpl.of(654, 'Braixen')
  public static readonly Delphox = SpeciesImpl.of(655, 'Delphox')
  public static readonly Froakie = SpeciesImpl.of(656, 'Froakie')
  public static readonly Frogadier = SpeciesImpl.of(657, 'Frogadier')
  public static readonly Greninja = SpeciesImpl.of(658, 'Greninja')
  public static readonly Bunnelby = SpeciesImpl.of(659, 'Bunnelby')
  public static readonly Diggersby = SpeciesImpl.of(660, 'Diggersby')
  public static readonly Fletchling = SpeciesImpl.of(661, 'Fletchling')
  public static readonly Fletchinder = SpeciesImpl.of(662, 'Fletchinder')
  public static readonly Talonflame = SpeciesImpl.of(663, 'Talonflame')
  public static readonly Scatterbug = SpeciesImpl.of(664, 'Scatterbug')
  public static readonly Spewpa = SpeciesImpl.of(665, 'Spewpa')
  public static readonly Vivillon = SpeciesImpl.of(666, 'Vivillon')
  public static readonly Litleo = SpeciesImpl.of(667, 'Litleo')
  public static readonly Pyroar = SpeciesImpl.of(668, 'Pyroar')
  public static readonly Flabebe = SpeciesImpl.of(669, 'Flabebe')
  public static readonly Floette = SpeciesImpl.of(670, 'Floette')
  public static readonly Florges = SpeciesImpl.of(671, 'Florges')
  public static readonly Skiddo = SpeciesImpl.of(672, 'Skiddo')
  public static readonly Gogoat = SpeciesImpl.of(673, 'Gogoat')
  public static readonly Pancham = SpeciesImpl.of(674, 'Pancham')
  public static readonly Pangoro = SpeciesImpl.of(675, 'Pangoro')
  public static readonly Furfrou = SpeciesImpl.of(676, 'Furfrou')
  public static readonly Espurr = SpeciesImpl.of(677, 'Espurr')
  public static readonly Meowstic = SpeciesImpl.of(678, 'Meowstic')
  public static readonly Honedge = SpeciesImpl.of(679, 'Honedge')
  public static readonly Doublade = SpeciesImpl.of(680, 'Doublade')
  public static readonly Aegislash = SpeciesImpl.of(681, 'Aegislash')
  public static readonly Spritzee = SpeciesImpl.of(682, 'Spritzee')
  public static readonly Aromatisse = SpeciesImpl.of(683, 'Aromatisse')
  public static readonly Swirlix = SpeciesImpl.of(684, 'Swirlix')
  public static readonly Slurpuff = SpeciesImpl.of(685, 'Slurpuff')
  public static readonly Inkay = SpeciesImpl.of(686, 'Inkay')
  public static readonly Malamar = SpeciesImpl.of(687, 'Malamar')
  public static readonly Binacle = SpeciesImpl.of(688, 'Binacle')
  public static readonly Barbaracle = SpeciesImpl.of(689, 'Barbaracle')
  public static readonly Skrelp = SpeciesImpl.of(690, 'Skrelp')
  public static readonly Dragalge = SpeciesImpl.of(691, 'Dragalge')
  public static readonly Clauncher = SpeciesImpl.of(692, 'Clauncher')
  public static readonly Clawitzer = SpeciesImpl.of(693, 'Clawitzer')
  public static readonly Helioptile = SpeciesImpl.of(694, 'Helioptile')
  public static readonly Heliolisk = SpeciesImpl.of(695, 'Heliolisk')
  public static readonly Tyrunt = SpeciesImpl.of(696, 'Tyrunt')
  public static readonly Tyrantrum = SpeciesImpl.of(697, 'Tyrantrum')
  public static readonly Amaura = SpeciesImpl.of(698, 'Amaura')
  public static readonly Aurorus = SpeciesImpl.of(699, 'Aurorus')
  public static readonly Sylveon = SpeciesImpl.of(700, 'Sylveon')
  public static readonly Hawlucha = SpeciesImpl.of(701, 'Hawlucha')
  public static readonly Dedenne = SpeciesImpl.of(702, 'Dedenne')
  public static readonly Carbink = SpeciesImpl.of(703, 'Carbink')
  public static readonly Goomy = SpeciesImpl.of(704, 'Goomy')
  public static readonly Sliggoo = SpeciesImpl.of(705, 'Sliggoo')
  public static readonly Goodra = SpeciesImpl.of(706, 'Goodra')
  public static readonly Klefki = SpeciesImpl.of(707, 'Klefki')
  public static readonly Phantump = SpeciesImpl.of(708, 'Phantump')
  public static readonly Trevenant = SpeciesImpl.of(709, 'Trevenant')
  public static readonly Pumpkaboo = SpeciesImpl.of(710, 'Pumpkaboo')
  public static readonly Gourgeist = SpeciesImpl.of(711, 'Gourgeist')
  public static readonly Bergmite = SpeciesImpl.of(712, 'Bergmite')
  public static readonly Avalugg = SpeciesImpl.of(713, 'Avalugg')
  public static readonly Noibat = SpeciesImpl.of(714, 'Noibat')
  public static readonly Noivern = SpeciesImpl.of(715, 'Noivern')
  public static readonly Xerneas = SpeciesImpl.of(716, 'Xerneas')
  public static readonly Yveltal = SpeciesImpl.of(717, 'Yveltal')
  public static readonly Zygarde = SpeciesImpl.of(718, 'Zygarde')
  public static readonly Diancie = SpeciesImpl.of(719, 'Diancie')
  public static readonly Hoopa = SpeciesImpl.of(720, 'Hoopa')
  public static readonly Volcanion = SpeciesImpl.of(721, 'Volcanion')
  public static readonly Rowlet = SpeciesImpl.of(722, 'Rowlet')
  public static readonly Dartrix = SpeciesImpl.of(723, 'Dartrix')
  public static readonly Decidueye = SpeciesImpl.of(724, 'Decidueye')
  public static readonly Litten = SpeciesImpl.of(725, 'Litten')
  public static readonly Torracat = SpeciesImpl.of(726, 'Torracat')
  public static readonly Incineroar = SpeciesImpl.of(727, 'Incineroar')
  public static readonly Popplio = SpeciesImpl.of(728, 'Popplio')
  public static readonly Brionne = SpeciesImpl.of(729, 'Brionne')
  public static readonly Primarina = SpeciesImpl.of(730, 'Primarina')
  public static readonly Pikipek = SpeciesImpl.of(731, 'Pikipek')
  public static readonly Trumbeak = SpeciesImpl.of(732, 'Trumbeak')
  public static readonly Toucannon = SpeciesImpl.of(733, 'Toucannon')
  public static readonly Yungoos = SpeciesImpl.of(734, 'Yungoos')
  public static readonly Gumshoos = SpeciesImpl.of(735, 'Gumshoos')
  public static readonly Grubbin = SpeciesImpl.of(736, 'Grubbin')
  public static readonly Charjabug = SpeciesImpl.of(737, 'Charjabug')
  public static readonly Vikavolt = SpeciesImpl.of(738, 'Vikavolt')
  public static readonly Crabrawler = SpeciesImpl.of(739, 'Crabrawler')
  public static readonly Crabominable = SpeciesImpl.of(740, 'Crabominable')
  public static readonly Oricorio = SpeciesImpl.of(741, 'Oricorio')
  public static readonly Cutiefly = SpeciesImpl.of(742, 'Cutiefly')
  public static readonly Ribombee = SpeciesImpl.of(743, 'Ribombee')
  public static readonly Rockruff = SpeciesImpl.of(744, 'Rockruff')
  public static readonly Lycanroc = SpeciesImpl.of(745, 'Lycanroc')
  public static readonly Wishiwashi = SpeciesImpl.of(746, 'Wishiwashi')
  public static readonly Mareanie = SpeciesImpl.of(747, 'Mareanie')
  public static readonly Toxapex = SpeciesImpl.of(748, 'Toxapex')
  public static readonly Mudbray = SpeciesImpl.of(749, 'Mudbray')
  public static readonly Mudsdale = SpeciesImpl.of(750, 'Mudsdale')
  public static readonly Dewpider = SpeciesImpl.of(751, 'Dewpider')
  public static readonly Araquanid = SpeciesImpl.of(752, 'Araquanid')
  public static readonly Fomantis = SpeciesImpl.of(753, 'Fomantis')
  public static readonly Lurantis = SpeciesImpl.of(754, 'Lurantis')
  public static readonly Morelull = SpeciesImpl.of(755, 'Morelull')
  public static readonly Shiinotic = SpeciesImpl.of(756, 'Shiinotic')
  public static readonly Salandit = SpeciesImpl.of(757, 'Salandit')
  public static readonly Salazzle = SpeciesImpl.of(758, 'Salazzle')
  public static readonly Stufful = SpeciesImpl.of(759, 'Stufful')
  public static readonly Bewear = SpeciesImpl.of(760, 'Bewear')
  public static readonly Bounsweet = SpeciesImpl.of(761, 'Bounsweet')
  public static readonly Steenee = SpeciesImpl.of(762, 'Steenee')
  public static readonly Tsareena = SpeciesImpl.of(763, 'Tsareena')
  public static readonly Comfey = SpeciesImpl.of(764, 'Comfey')
  public static readonly Oranguru = SpeciesImpl.of(765, 'Oranguru')
  public static readonly Passimian = SpeciesImpl.of(766, 'Passimian')
  public static readonly Wimpod = SpeciesImpl.of(767, 'Wimpod')
  public static readonly Golisopod = SpeciesImpl.of(768, 'Golisopod')
  public static readonly Sandygast = SpeciesImpl.of(769, 'Sandygast')
  public static readonly Palossand = SpeciesImpl.of(770, 'Palossand')
  public static readonly Pyukumuku = SpeciesImpl.of(771, 'Pyukumuku')
  public static readonly TypeNull = SpeciesImpl.of(772, 'TypeNull')
  public static readonly Silvally = SpeciesImpl.of(773, 'Silvally')
  public static readonly Minior = SpeciesImpl.of(774, 'Minior')
  public static readonly Komala = SpeciesImpl.of(775, 'Komala')
  public static readonly Turtonator = SpeciesImpl.of(776, 'Turtonator')
  public static readonly Togedemaru = SpeciesImpl.of(777, 'Togedemaru')
  public static readonly Mimikyu = SpeciesImpl.of(778, 'Mimikyu')
  public static readonly Bruxish = SpeciesImpl.of(779, 'Bruxish')
  public static readonly Drampa = SpeciesImpl.of(780, 'Drampa')
  public static readonly Dhelmise = SpeciesImpl.of(781, 'Dhelmise')
  public static readonly Jangmoo = SpeciesImpl.of(782, 'Jangmo-o')
  public static readonly Hakamoo = SpeciesImpl.of(783, 'Hakamo-o')
  public static readonly Kommoo = SpeciesImpl.of(784, 'Kommo-o')
  public static readonly TapuKoko = SpeciesImpl.of(785, 'TapuKoko')
  public static readonly TapuLele = SpeciesImpl.of(786, 'TapuLele')
  public static readonly TapuBulu = SpeciesImpl.of(787, 'TapuBulu')
  public static readonly TapuFini = SpeciesImpl.of(788, 'TapuFini')
  public static readonly Cosmog = SpeciesImpl.of(789, 'Cosmog')
  public static readonly Cosmoem = SpeciesImpl.of(790, 'Cosmoem')
  public static readonly Solgaleo = SpeciesImpl.of(791, 'Solgaleo')
  public static readonly Lunala = SpeciesImpl.of(792, 'Lunala')
  public static readonly Nihilego = SpeciesImpl.of(793, 'Nihilego')
  public static readonly Buzzwole = SpeciesImpl.of(794, 'Buzzwole')
  public static readonly Pheromosa = SpeciesImpl.of(795, 'Pheromosa')
  public static readonly Xurkitree = SpeciesImpl.of(796, 'Xurkitree')
  public static readonly Celesteela = SpeciesImpl.of(797, 'Celesteela')
  public static readonly Kartana = SpeciesImpl.of(798, 'Kartana')
  public static readonly Guzzlord = SpeciesImpl.of(799, 'Guzzlord')
  public static readonly Necrozma = SpeciesImpl.of(800, 'Necrozma')
  public static readonly Magearna = SpeciesImpl.of(801, 'Magearna')
  public static readonly Marshadow = SpeciesImpl.of(802, 'Marshadow')
  public static readonly Poipole = SpeciesImpl.of(803, 'Poipole')
  public static readonly Naganadel = SpeciesImpl.of(804, 'Naganadel')
  public static readonly Stakataka = SpeciesImpl.of(805, 'Stakataka')
  public static readonly Blacephalon = SpeciesImpl.of(806, 'Blacephalon')
  public static readonly Zeraora = SpeciesImpl.of(807, 'Zeraora')
  public static readonly Meltan = SpeciesImpl.of(808, 'Meltan')
  public static readonly Melmetal = SpeciesImpl.of(809, 'Melmetal')
  public static readonly Grookey = SpeciesImpl.of(810, 'Grookey')
  public static readonly Thwackey = SpeciesImpl.of(811, 'Thwackey')
  public static readonly Rillaboom = SpeciesImpl.of(812, 'Rillaboom')
  public static readonly Scorbunny = SpeciesImpl.of(813, 'Scorbunny')
  public static readonly Raboot = SpeciesImpl.of(814, 'Raboot')
  public static readonly Cinderace = SpeciesImpl.of(815, 'Cinderace')
  public static readonly Sobble = SpeciesImpl.of(816, 'Sobble')
  public static readonly Drizzile = SpeciesImpl.of(817, 'Drizzile')
  public static readonly Inteleon = SpeciesImpl.of(818, 'Inteleon')
  public static readonly Skwovet = SpeciesImpl.of(819, 'Skwovet')
  public static readonly Greedent = SpeciesImpl.of(820, 'Greedent')
  public static readonly Rookidee = SpeciesImpl.of(821, 'Rookidee')
  public static readonly Corvisquire = SpeciesImpl.of(822, 'Corvisquire')
  public static readonly Corviknight = SpeciesImpl.of(823, 'Corviknight')
  public static readonly Blipbug = SpeciesImpl.of(824, 'Blipbug')
  public static readonly Dottler = SpeciesImpl.of(825, 'Dottler')
  public static readonly Orbeetle = SpeciesImpl.of(826, 'Orbeetle')
  public static readonly Nickit = SpeciesImpl.of(827, 'Nickit')
  public static readonly Thievul = SpeciesImpl.of(828, 'Thievul')
  public static readonly Gossifleur = SpeciesImpl.of(829, 'Gossifleur')
  public static readonly Eldegoss = SpeciesImpl.of(830, 'Eldegoss')
  public static readonly Wooloo = SpeciesImpl.of(831, 'Wooloo')
  public static readonly Dubwool = SpeciesImpl.of(832, 'Dubwool')
  public static readonly Chewtle = SpeciesImpl.of(833, 'Chewtle')
  public static readonly Drednaw = SpeciesImpl.of(834, 'Drednaw')
  public static readonly Yamper = SpeciesImpl.of(835, 'Yamper')
  public static readonly Boltund = SpeciesImpl.of(836, 'Boltund')
  public static readonly Rolycoly = SpeciesImpl.of(837, 'Rolycoly')
  public static readonly Carkol = SpeciesImpl.of(838, 'Carkol')
  public static readonly Coalossal = SpeciesImpl.of(839, 'Coalossal')
  public static readonly Applin = SpeciesImpl.of(840, 'Applin')
  public static readonly Flapple = SpeciesImpl.of(841, 'Flapple')
  public static readonly Appletun = SpeciesImpl.of(842, 'Appletun')
  public static readonly Silicobra = SpeciesImpl.of(843, 'Silicobra')
  public static readonly Sandaconda = SpeciesImpl.of(844, 'Sandaconda')
  public static readonly Cramorant = SpeciesImpl.of(845, 'Cramorant')
  public static readonly Arrokuda = SpeciesImpl.of(846, 'Arrokuda')
  public static readonly Barraskewda = SpeciesImpl.of(847, 'Barraskewda')
  public static readonly Toxel = SpeciesImpl.of(848, 'Toxel')
  public static readonly Toxtricity = SpeciesImpl.of(849, 'Toxtricity')
  public static readonly Sizzlipede = SpeciesImpl.of(850, 'Sizzlipede')
  public static readonly Centiskorch = SpeciesImpl.of(851, 'Centiskorch')
  public static readonly Clobbopus = SpeciesImpl.of(852, 'Clobbopus')
  public static readonly Grapploct = SpeciesImpl.of(853, 'Grapploct')
  public static readonly Sinistea = SpeciesImpl.of(854, 'Sinistea')
  public static readonly Polteageist = SpeciesImpl.of(855, 'Polteageist')
  public static readonly Hatenna = SpeciesImpl.of(856, 'Hatenna')
  public static readonly Hattrem = SpeciesImpl.of(857, 'Hattrem')
  public static readonly Hatterene = SpeciesImpl.of(858, 'Hatterene')
  public static readonly Impidimp = SpeciesImpl.of(859, 'Impidimp')
  public static readonly Morgrem = SpeciesImpl.of(860, 'Morgrem')
  public static readonly Grimmsnarl = SpeciesImpl.of(861, 'Grimmsnarl')
  public static readonly Obstagoon = SpeciesImpl.of(862, 'Obstagoon')
  public static readonly Perrserker = SpeciesImpl.of(863, 'Perrserker')
  public static readonly Cursola = SpeciesImpl.of(864, 'Cursola')
  public static readonly Sirfetchd = SpeciesImpl.of(865, 'Sirfetchd')
  public static readonly MrRime = SpeciesImpl.of(866, 'MrRime')
  public static readonly Runerigus = SpeciesImpl.of(867, 'Runerigus')
  public static readonly Milcery = SpeciesImpl.of(868, 'Milcery')
  public static readonly Alcremie = SpeciesImpl.of(869, 'Alcremie')
  public static readonly Falinks = SpeciesImpl.of(870, 'Falinks')
  public static readonly Pincurchin = SpeciesImpl.of(871, 'Pincurchin')
  public static readonly Snom = SpeciesImpl.of(872, 'Snom')
  public static readonly Frosmoth = SpeciesImpl.of(873, 'Frosmoth')
  public static readonly Stonjourner = SpeciesImpl.of(874, 'Stonjourner')
  public static readonly Eiscue = SpeciesImpl.of(875, 'Eiscue')
  public static readonly Indeedee = SpeciesImpl.of(876, 'Indeedee')
  public static readonly Morpeko = SpeciesImpl.of(877, 'Morpeko')
  public static readonly Cufant = SpeciesImpl.of(878, 'Cufant')
  public static readonly Copperajah = SpeciesImpl.of(879, 'Copperajah')
  public static readonly Dracozolt = SpeciesImpl.of(880, 'Dracozolt')
  public static readonly Arctozolt = SpeciesImpl.of(881, 'Arctozolt')
  public static readonly Dracovish = SpeciesImpl.of(882, 'Dracovish')
  public static readonly Arctovish = SpeciesImpl.of(883, 'Arctovish')
  public static readonly Duraludon = SpeciesImpl.of(884, 'Duraludon')
  public static readonly Dreepy = SpeciesImpl.of(885, 'Dreepy')
  public static readonly Drakloak = SpeciesImpl.of(886, 'Drakloak')
  public static readonly Dragapult = SpeciesImpl.of(887, 'Dragapult')
  public static readonly Zacian = SpeciesImpl.of(888, 'Zacian')
  public static readonly Zamazenta = SpeciesImpl.of(889, 'Zamazenta')
  public static readonly Eternatus = SpeciesImpl.of(890, 'Eternatus')
  public static readonly Kubfu = SpeciesImpl.of(891, 'Kubfu')
  public static readonly Urshifu = SpeciesImpl.of(892, 'Urshifu')
  public static readonly Zarude = SpeciesImpl.of(893, 'Zarude')
  public static readonly Regieleki = SpeciesImpl.of(894, 'Regieleki')
  public static readonly Regidrago = SpeciesImpl.of(895, 'Regidrago')
  public static readonly Glastrier = SpeciesImpl.of(896, 'Glastrier')
  public static readonly Spectrier = SpeciesImpl.of(897, 'Spectrier')
  public static readonly Calyrex = SpeciesImpl.of(898, 'Calyrex')

  protected static readonly legendaries: Species[] = []
  protected static readonly ultrabeasts: Species[] = []
  protected static readonly allPokemons: Set<Species> = new Set()

  protected constructor(
    protected readonly dex: number,
    protected readonly name: string
  ) {
    Species.allPokemons.add(this)
  }

  /**
   * Gets the immutable readonly array of species that are considered legendary.
   *
   * @returns {ReadonlyArray<Species>} The immutable array of legendary pokemons
   */
  public static getLegendaries(): ReadonlyArray<Species> {
    return [...Species.legendaries]
  }

  /**
   * Gets the immutable readonly array of species that are considered ultrabeast.
   *
   * @returns {ReadonlyArray<Species>} The immutable array of ultrabeast pokemons
   */
  public static getUltrabeasts(): ReadonlyArray<Species> {
    return [...Species.ultrabeasts]
  }

  /**
   * Gets the readonly set of all the pokemon species.
   *
   * @returns {ReadonlySet<Species>} The readonly set of all the pokemon species
   */
  public static getAllPokemons(): ReadonlySet<Species> {
    return new Set([...Species.allPokemons])
  }

  /**
   * Returns whether the given name is a valid Pokemon name.
   *
   * @param {string} name The name of the Pokemon to check
   * @returns {boolean} Whether the given name is a valid species name
   */
  public static has(name: string): boolean {
    return Species.getFromName(name) !== null
  }

  /**
   * Gets the corresponding species with the given name.
   *
   * @param {string} name The name of the Pokemon to get
   * @returns {Species | null} The species that matches the given name, or null if no such species exists.
   * @see {@link has has()}
   */
  public static getFromName(name: string): Species | null {
    for (const pokemon of Species.allPokemons) {
      if (
        pokemon.getName().toLowerCase() === name.toLowerCase() ||
        pokemon.getLocalizedName().toLowerCase() === name.toLowerCase()
      )
        return pokemon
    }

    return null
  }

  /**
   * Gets the corresponding species with the given pokedex.
   *
   * @param {number | string} dex - The pokedex number of the pokemon.
   * @returns {Species | null} The species that matches the given pokedex, or null if no such species exists.
   */
  public static getFromDex(dex: number | string): Species | null {
    for (const species of Species.allPokemons) {
      if (
        (typeof dex === `number` &&
          species.getNationalPokedex().asNumber() === dex) ||
        (typeof dex === `string` &&
          species.getNationalPokedex().asString() === dex)
      ) {
        return species
      }
    }

    return null
  }

  /**
   * Returns whether the species is a legendary pokemon.
   *
   * @returns {boolean} Whether the species is a legendary pokemon or not
   */
  public abstract isLegendary(): boolean

  /**
   * Returns whether the species is a ultrabeast.
   *
   * @returns {boolean} Whether the species is a ultrabeast or not
   */
  public abstract isUltraBeast(): boolean

  /**
   * Gets the name of the species.
   *
   * @returns {string} The name of the species
   */
  public abstract getName(): string

  /**
   * Gets the localized name of the species.
   *
   * @returns {string} The localized name of the species
   */
  public abstract getLocalizedName(): string

  /**
   * Gets the localization key of the species.
   *
   * @returns {string} The localization key of the species
   */
  public abstract getLocalizationKey(): string

  /**
   * Gets the Pokedex wrapper of the species.
   *
   * <p>
   *   It returns a wrapper around the national pokedex number of the species,
   *   which could be used to get the national pokedex number as a string with
   *   3 digits, or as a number.
   * </p>
   *
   * @returns {{ asNumber(): number, asString(): string }} The Pokedex wrapper of the species
   */
  public abstract getNationalPokedex(): {
    asNumber(): number
    asString(): string
  }

  /**
   * Indicates whether some other object is equal to this one.
   *
   * <pre>
   *   This method takes one parameter, `other`, which is the EnumSpecies
   *   to compare to. It returns `true` if the other object is an instance
   *   of EnumSpecies or has the same national dex number and name as this one.
   *   Otherwise, it returns `false`.
   *
   *   This method is strongly inspired by the `equals` method of the Java Object class.
   * </pre>
   *
   * @param {Species} other The reference object with which to compare
   * @returns {boolean} `true` if this object is the same as the other object, `false` otherwise
   */
  public abstract equals(other: any): boolean
}
