import i18next from 'i18next'

export class EnumSpecies {
  public static PokemonSet: ReadonlySet<EnumSpecies> = new Set()

  public static MissingNo = EnumSpecies.of(0, 'MissingNo')
  public static Bulbasaur = EnumSpecies.of(1, 'Bulbasaur')
  public static Ivysaur = EnumSpecies.of(2, 'Ivysaur')
  public static Venusaur = EnumSpecies.of(3, 'Venusaur')
  public static Charmander = EnumSpecies.of(4, 'Charmander')
  public static Charmeleon = EnumSpecies.of(5, 'Charmeleon')
  public static Charizard = EnumSpecies.of(6, 'Charizard')
  public static Squirtle = EnumSpecies.of(7, 'Squirtle')
  public static Wartortle = EnumSpecies.of(8, 'Wartortle')
  public static Blastoise = EnumSpecies.of(9, 'Blastoise')
  public static Caterpie = EnumSpecies.of(10, 'Caterpie')
  public static Metapod = EnumSpecies.of(11, 'Metapod')
  public static Butterfree = EnumSpecies.of(12, 'Butterfree')
  public static Weedle = EnumSpecies.of(13, 'Weedle')
  public static Kakuna = EnumSpecies.of(14, 'Kakuna')
  public static Beedrill = EnumSpecies.of(15, 'Beedrill')
  public static Pidgey = EnumSpecies.of(16, 'Pidgey')
  public static Pidgeotto = EnumSpecies.of(17, 'Pidgeotto')
  public static Pidgeot = EnumSpecies.of(18, 'Pidgeot')
  public static Rattata = EnumSpecies.of(19, 'Rattata')
  public static Raticate = EnumSpecies.of(20, 'Raticate')
  public static Spearow = EnumSpecies.of(21, 'Spearow')
  public static Fearow = EnumSpecies.of(22, 'Fearow')
  public static Ekans = EnumSpecies.of(23, 'Ekans')
  public static Arbok = EnumSpecies.of(24, 'Arbok')
  public static Pikachu = EnumSpecies.of(25, 'Pikachu')
  public static Raichu = EnumSpecies.of(26, 'Raichu')
  public static Sandshrew = EnumSpecies.of(27, 'Sandshrew')
  public static Sandslash = EnumSpecies.of(28, 'Sandslash')
  public static Nidoranfemale = EnumSpecies.of(29, 'Nidoranfemale')
  public static Nidorina = EnumSpecies.of(30, 'Nidorina')
  public static Nidoqueen = EnumSpecies.of(31, 'Nidoqueen')
  public static Nidoranmale = EnumSpecies.of(32, 'Nidoranmale')
  public static Nidorino = EnumSpecies.of(33, 'Nidorino')
  public static Nidoking = EnumSpecies.of(34, 'Nidoking')
  public static Clefairy = EnumSpecies.of(35, 'Clefairy')
  public static Clefable = EnumSpecies.of(36, 'Clefable')
  public static Vulpix = EnumSpecies.of(37, 'Vulpix')
  public static Ninetales = EnumSpecies.of(38, 'Ninetales')
  public static Jigglypuff = EnumSpecies.of(39, 'Jigglypuff')
  public static Wigglytuff = EnumSpecies.of(40, 'Wigglytuff')
  public static Zubat = EnumSpecies.of(41, 'Zubat')
  public static Golbat = EnumSpecies.of(42, 'Golbat')
  public static Oddish = EnumSpecies.of(43, 'Oddish')
  public static Gloom = EnumSpecies.of(44, 'Gloom')
  public static Vileplume = EnumSpecies.of(45, 'Vileplume')
  public static Paras = EnumSpecies.of(46, 'Paras')
  public static Parasect = EnumSpecies.of(47, 'Parasect')
  public static Venonat = EnumSpecies.of(48, 'Venonat')
  public static Venomoth = EnumSpecies.of(49, 'Venomoth')
  public static Diglett = EnumSpecies.of(50, 'Diglett')
  public static Dugtrio = EnumSpecies.of(51, 'Dugtrio')
  public static Meowth = EnumSpecies.of(52, 'Meowth')
  public static Persian = EnumSpecies.of(53, 'Persian')
  public static Psyduck = EnumSpecies.of(54, 'Psyduck')
  public static Golduck = EnumSpecies.of(55, 'Golduck')
  public static Mankey = EnumSpecies.of(56, 'Mankey')
  public static Primeape = EnumSpecies.of(57, 'Primeape')
  public static Growlithe = EnumSpecies.of(58, 'Growlithe')
  public static Arcanine = EnumSpecies.of(59, 'Arcanine')
  public static Poliwag = EnumSpecies.of(60, 'Poliwag')
  public static Poliwhirl = EnumSpecies.of(61, 'Poliwhirl')
  public static Poliwrath = EnumSpecies.of(62, 'Poliwrath')
  public static Abra = EnumSpecies.of(63, 'Abra')
  public static Kadabra = EnumSpecies.of(64, 'Kadabra')
  public static Alakazam = EnumSpecies.of(65, 'Alakazam')
  public static Machop = EnumSpecies.of(66, 'Machop')
  public static Machoke = EnumSpecies.of(67, 'Machoke')
  public static Machamp = EnumSpecies.of(68, 'Machamp')
  public static Bellsprout = EnumSpecies.of(69, 'Bellsprout')
  public static Weepinbell = EnumSpecies.of(70, 'Weepinbell')
  public static Victreebel = EnumSpecies.of(71, 'Victreebel')
  public static Tentacool = EnumSpecies.of(72, 'Tentacool')
  public static Tentacruel = EnumSpecies.of(73, 'Tentacruel')
  public static Geodude = EnumSpecies.of(74, 'Geodude')
  public static Graveler = EnumSpecies.of(75, 'Graveler')
  public static Golem = EnumSpecies.of(76, 'Golem')
  public static Ponyta = EnumSpecies.of(77, 'Ponyta')
  public static Rapidash = EnumSpecies.of(78, 'Rapidash')
  public static Slowpoke = EnumSpecies.of(79, 'Slowpoke')
  public static Slowbro = EnumSpecies.of(80, 'Slowbro')
  public static Magnemite = EnumSpecies.of(81, 'Magnemite')
  public static Magneton = EnumSpecies.of(82, 'Magneton')
  public static Farfetchd = EnumSpecies.of(83, 'Farfetchd')
  public static Doduo = EnumSpecies.of(84, 'Doduo')
  public static Dodrio = EnumSpecies.of(85, 'Dodrio')
  public static Seel = EnumSpecies.of(86, 'Seel')
  public static Dewgong = EnumSpecies.of(87, 'Dewgong')
  public static Grimer = EnumSpecies.of(88, 'Grimer')
  public static Muk = EnumSpecies.of(89, 'Muk')
  public static Shellder = EnumSpecies.of(90, 'Shellder')
  public static Cloyster = EnumSpecies.of(91, 'Cloyster')
  public static Gastly = EnumSpecies.of(92, 'Gastly')
  public static Haunter = EnumSpecies.of(93, 'Haunter')
  public static Gengar = EnumSpecies.of(94, 'Gengar')
  public static Onix = EnumSpecies.of(95, 'Onix')
  public static Drowzee = EnumSpecies.of(96, 'Drowzee')
  public static Hypno = EnumSpecies.of(97, 'Hypno')
  public static Krabby = EnumSpecies.of(98, 'Krabby')
  public static Kingler = EnumSpecies.of(99, 'Kingler')
  public static Voltorb = EnumSpecies.of(100, 'Voltorb')
  public static Electrode = EnumSpecies.of(101, 'Electrode')
  public static Exeggcute = EnumSpecies.of(102, 'Exeggcute')
  public static Exeggutor = EnumSpecies.of(103, 'Exeggutor')
  public static Cubone = EnumSpecies.of(104, 'Cubone')
  public static Marowak = EnumSpecies.of(105, 'Marowak')
  public static Hitmonlee = EnumSpecies.of(106, 'Hitmonlee')
  public static Hitmonchan = EnumSpecies.of(107, 'Hitmonchan')
  public static Lickitung = EnumSpecies.of(108, 'Lickitung')
  public static Koffing = EnumSpecies.of(109, 'Koffing')
  public static Weezing = EnumSpecies.of(110, 'Weezing')
  public static Rhyhorn = EnumSpecies.of(111, 'Rhyhorn')
  public static Rhydon = EnumSpecies.of(112, 'Rhydon')
  public static Chansey = EnumSpecies.of(113, 'Chansey')
  public static Tangela = EnumSpecies.of(114, 'Tangela')
  public static Kangaskhan = EnumSpecies.of(115, 'Kangaskhan')
  public static Horsea = EnumSpecies.of(116, 'Horsea')
  public static Seadra = EnumSpecies.of(117, 'Seadra')
  public static Goldeen = EnumSpecies.of(118, 'Goldeen')
  public static Seaking = EnumSpecies.of(119, 'Seaking')
  public static Staryu = EnumSpecies.of(120, 'Staryu')
  public static Starmie = EnumSpecies.of(121, 'Starmie')
  public static MrMime = EnumSpecies.of(122, 'MrMime')
  public static Scyther = EnumSpecies.of(123, 'Scyther')
  public static Jynx = EnumSpecies.of(124, 'Jynx')
  public static Electabuzz = EnumSpecies.of(125, 'Electabuzz')
  public static Magmar = EnumSpecies.of(126, 'Magmar')
  public static Pinsir = EnumSpecies.of(127, 'Pinsir')
  public static Tauros = EnumSpecies.of(128, 'Tauros')
  public static Magikarp = EnumSpecies.of(129, 'Magikarp')
  public static Gyarados = EnumSpecies.of(130, 'Gyarados')
  public static Lapras = EnumSpecies.of(131, 'Lapras')
  public static Ditto = EnumSpecies.of(132, 'Ditto')
  public static Eevee = EnumSpecies.of(133, 'Eevee')
  public static Vaporeon = EnumSpecies.of(134, 'Vaporeon')
  public static Jolteon = EnumSpecies.of(135, 'Jolteon')
  public static Flareon = EnumSpecies.of(136, 'Flareon')
  public static Porygon = EnumSpecies.of(137, 'Porygon')
  public static Omanyte = EnumSpecies.of(138, 'Omanyte')
  public static Omastar = EnumSpecies.of(139, 'Omastar')
  public static Kabuto = EnumSpecies.of(140, 'Kabuto')
  public static Kabutops = EnumSpecies.of(141, 'Kabutops')
  public static Aerodactyl = EnumSpecies.of(142, 'Aerodactyl')
  public static Snorlax = EnumSpecies.of(143, 'Snorlax')
  public static Articuno = EnumSpecies.of(144, 'Articuno')
  public static Zapdos = EnumSpecies.of(145, 'Zapdos')
  public static Moltres = EnumSpecies.of(146, 'Moltres')
  public static Dratini = EnumSpecies.of(147, 'Dratini')
  public static Dragonair = EnumSpecies.of(148, 'Dragonair')
  public static Dragonite = EnumSpecies.of(149, 'Dragonite')
  public static Mewtwo = EnumSpecies.of(150, 'Mewtwo')
  public static Mew = EnumSpecies.of(151, 'Mew')
  public static Chikorita = EnumSpecies.of(152, 'Chikorita')
  public static Bayleef = EnumSpecies.of(153, 'Bayleef')
  public static Meganium = EnumSpecies.of(154, 'Meganium')
  public static Cyndaquil = EnumSpecies.of(155, 'Cyndaquil')
  public static Quilava = EnumSpecies.of(156, 'Quilava')
  public static Typhlosion = EnumSpecies.of(157, 'Typhlosion')
  public static Totodile = EnumSpecies.of(158, 'Totodile')
  public static Croconaw = EnumSpecies.of(159, 'Croconaw')
  public static Feraligatr = EnumSpecies.of(160, 'Feraligatr')
  public static Sentret = EnumSpecies.of(161, 'Sentret')
  public static Furret = EnumSpecies.of(162, 'Furret')
  public static Hoothoot = EnumSpecies.of(163, 'Hoothoot')
  public static Noctowl = EnumSpecies.of(164, 'Noctowl')
  public static Ledyba = EnumSpecies.of(165, 'Ledyba')
  public static Ledian = EnumSpecies.of(166, 'Ledian')
  public static Spinarak = EnumSpecies.of(167, 'Spinarak')
  public static Ariados = EnumSpecies.of(168, 'Ariados')
  public static Crobat = EnumSpecies.of(169, 'Crobat')
  public static Chinchou = EnumSpecies.of(170, 'Chinchou')
  public static Lanturn = EnumSpecies.of(171, 'Lanturn')
  public static Pichu = EnumSpecies.of(172, 'Pichu')
  public static Cleffa = EnumSpecies.of(173, 'Cleffa')
  public static Igglybuff = EnumSpecies.of(174, 'Igglybuff')
  public static Togepi = EnumSpecies.of(175, 'Togepi')
  public static Togetic = EnumSpecies.of(176, 'Togetic')
  public static Natu = EnumSpecies.of(177, 'Natu')
  public static Xatu = EnumSpecies.of(178, 'Xatu')
  public static Mareep = EnumSpecies.of(179, 'Mareep')
  public static Flaaffy = EnumSpecies.of(180, 'Flaaffy')
  public static Ampharos = EnumSpecies.of(181, 'Ampharos')
  public static Bellossom = EnumSpecies.of(182, 'Bellossom')
  public static Marill = EnumSpecies.of(183, 'Marill')
  public static Azumarill = EnumSpecies.of(184, 'Azumarill')
  public static Sudowoodo = EnumSpecies.of(185, 'Sudowoodo')
  public static Politoed = EnumSpecies.of(186, 'Politoed')
  public static Hoppip = EnumSpecies.of(187, 'Hoppip')
  public static Skiploom = EnumSpecies.of(188, 'Skiploom')
  public static Jumpluff = EnumSpecies.of(189, 'Jumpluff')
  public static Aipom = EnumSpecies.of(190, 'Aipom')
  public static Sunkern = EnumSpecies.of(191, 'Sunkern')
  public static Sunflora = EnumSpecies.of(192, 'Sunflora')
  public static Yanma = EnumSpecies.of(193, 'Yanma')
  public static Wooper = EnumSpecies.of(194, 'Wooper')
  public static Quagsire = EnumSpecies.of(195, 'Quagsire')
  public static Espeon = EnumSpecies.of(196, 'Espeon')
  public static Umbreon = EnumSpecies.of(197, 'Umbreon')
  public static Murkrow = EnumSpecies.of(198, 'Murkrow')
  public static Slowking = EnumSpecies.of(199, 'Slowking')
  public static Misdreavus = EnumSpecies.of(200, 'Misdreavus')
  public static Unown = EnumSpecies.of(201, 'Unown')
  public static Wobbuffet = EnumSpecies.of(202, 'Wobbuffet')
  public static Girafarig = EnumSpecies.of(203, 'Girafarig')
  public static Pineco = EnumSpecies.of(204, 'Pineco')
  public static Forretress = EnumSpecies.of(205, 'Forretress')
  public static Dunsparce = EnumSpecies.of(206, 'Dunsparce')
  public static Gligar = EnumSpecies.of(207, 'Gligar')
  public static Steelix = EnumSpecies.of(208, 'Steelix')
  public static Snubbull = EnumSpecies.of(209, 'Snubbull')
  public static Granbull = EnumSpecies.of(210, 'Granbull')
  public static Qwilfish = EnumSpecies.of(211, 'Qwilfish')
  public static Scizor = EnumSpecies.of(212, 'Scizor')
  public static Shuckle = EnumSpecies.of(213, 'Shuckle')
  public static Heracross = EnumSpecies.of(214, 'Heracross')
  public static Sneasel = EnumSpecies.of(215, 'Sneasel')
  public static Teddiursa = EnumSpecies.of(216, 'Teddiursa')
  public static Ursaring = EnumSpecies.of(217, 'Ursaring')
  public static Slugma = EnumSpecies.of(218, 'Slugma')
  public static Magcargo = EnumSpecies.of(219, 'Magcargo')
  public static Swinub = EnumSpecies.of(220, 'Swinub')
  public static Piloswine = EnumSpecies.of(221, 'Piloswine')
  public static Corsola = EnumSpecies.of(222, 'Corsola')
  public static Remoraid = EnumSpecies.of(223, 'Remoraid')
  public static Octillery = EnumSpecies.of(224, 'Octillery')
  public static Delibird = EnumSpecies.of(225, 'Delibird')
  public static Mantine = EnumSpecies.of(226, 'Mantine')
  public static Skarmory = EnumSpecies.of(227, 'Skarmory')
  public static Houndour = EnumSpecies.of(228, 'Houndour')
  public static Houndoom = EnumSpecies.of(229, 'Houndoom')
  public static Kingdra = EnumSpecies.of(230, 'Kingdra')
  public static Phanpy = EnumSpecies.of(231, 'Phanpy')
  public static Donphan = EnumSpecies.of(232, 'Donphan')
  public static Porygon2 = EnumSpecies.of(233, 'Porygon2')
  public static Stantler = EnumSpecies.of(234, 'Stantler')
  public static Smeargle = EnumSpecies.of(235, 'Smeargle')
  public static Tyrogue = EnumSpecies.of(236, 'Tyrogue')
  public static Hitmontop = EnumSpecies.of(237, 'Hitmontop')
  public static Smoochum = EnumSpecies.of(238, 'Smoochum')
  public static Elekid = EnumSpecies.of(239, 'Elekid')
  public static Magby = EnumSpecies.of(240, 'Magby')
  public static Miltank = EnumSpecies.of(241, 'Miltank')
  public static Blissey = EnumSpecies.of(242, 'Blissey')
  public static Raikou = EnumSpecies.of(243, 'Raikou')
  public static Entei = EnumSpecies.of(244, 'Entei')
  public static Suicune = EnumSpecies.of(245, 'Suicune')
  public static Larvitar = EnumSpecies.of(246, 'Larvitar')
  public static Pupitar = EnumSpecies.of(247, 'Pupitar')
  public static Tyranitar = EnumSpecies.of(248, 'Tyranitar')
  public static Lugia = EnumSpecies.of(249, 'Lugia')
  public static Hooh = EnumSpecies.of(250, 'Ho-Oh')
  public static Celebi = EnumSpecies.of(251, 'Celebi')
  public static Treecko = EnumSpecies.of(252, 'Treecko')
  public static Grovyle = EnumSpecies.of(253, 'Grovyle')
  public static Sceptile = EnumSpecies.of(254, 'Sceptile')
  public static Torchic = EnumSpecies.of(255, 'Torchic')
  public static Combusken = EnumSpecies.of(256, 'Combusken')
  public static Blaziken = EnumSpecies.of(257, 'Blaziken')
  public static Mudkip = EnumSpecies.of(258, 'Mudkip')
  public static Marshtomp = EnumSpecies.of(259, 'Marshtomp')
  public static Swampert = EnumSpecies.of(260, 'Swampert')
  public static Poochyena = EnumSpecies.of(261, 'Poochyena')
  public static Mightyena = EnumSpecies.of(262, 'Mightyena')
  public static Zigzagoon = EnumSpecies.of(263, 'Zigzagoon')
  public static Linoone = EnumSpecies.of(264, 'Linoone')
  public static Wurmple = EnumSpecies.of(265, 'Wurmple')
  public static Silcoon = EnumSpecies.of(266, 'Silcoon')
  public static Beautifly = EnumSpecies.of(267, 'Beautifly')
  public static Cascoon = EnumSpecies.of(268, 'Cascoon')
  public static Dustox = EnumSpecies.of(269, 'Dustox')
  public static Lotad = EnumSpecies.of(270, 'Lotad')
  public static Lombre = EnumSpecies.of(271, 'Lombre')
  public static Ludicolo = EnumSpecies.of(272, 'Ludicolo')
  public static Seedot = EnumSpecies.of(273, 'Seedot')
  public static Nuzleaf = EnumSpecies.of(274, 'Nuzleaf')
  public static Shiftry = EnumSpecies.of(275, 'Shiftry')
  public static Taillow = EnumSpecies.of(276, 'Taillow')
  public static Swellow = EnumSpecies.of(277, 'Swellow')
  public static Wingull = EnumSpecies.of(278, 'Wingull')
  public static Pelipper = EnumSpecies.of(279, 'Pelipper')
  public static Ralts = EnumSpecies.of(280, 'Ralts')
  public static Kirlia = EnumSpecies.of(281, 'Kirlia')
  public static Gardevoir = EnumSpecies.of(282, 'Gardevoir')
  public static Surskit = EnumSpecies.of(283, 'Surskit')
  public static Masquerain = EnumSpecies.of(284, 'Masquerain')
  public static Shroomish = EnumSpecies.of(285, 'Shroomish')
  public static Breloom = EnumSpecies.of(286, 'Breloom')
  public static Slakoth = EnumSpecies.of(287, 'Slakoth')
  public static Vigoroth = EnumSpecies.of(288, 'Vigoroth')
  public static Slaking = EnumSpecies.of(289, 'Slaking')
  public static Nincada = EnumSpecies.of(290, 'Nincada')
  public static Ninjask = EnumSpecies.of(291, 'Ninjask')
  public static Shedinja = EnumSpecies.of(292, 'Shedinja')
  public static Whismur = EnumSpecies.of(293, 'Whismur')
  public static Loudred = EnumSpecies.of(294, 'Loudred')
  public static Exploud = EnumSpecies.of(295, 'Exploud')
  public static Makuhita = EnumSpecies.of(296, 'Makuhita')
  public static Hariyama = EnumSpecies.of(297, 'Hariyama')
  public static Azurill = EnumSpecies.of(298, 'Azurill')
  public static Nosepass = EnumSpecies.of(299, 'Nosepass')
  public static Skitty = EnumSpecies.of(300, 'Skitty')
  public static Delcatty = EnumSpecies.of(301, 'Delcatty')
  public static Sableye = EnumSpecies.of(302, 'Sableye')
  public static Mawile = EnumSpecies.of(303, 'Mawile')
  public static Aron = EnumSpecies.of(304, 'Aron')
  public static Lairon = EnumSpecies.of(305, 'Lairon')
  public static Aggron = EnumSpecies.of(306, 'Aggron')
  public static Meditite = EnumSpecies.of(307, 'Meditite')
  public static Medicham = EnumSpecies.of(308, 'Medicham')
  public static Electrike = EnumSpecies.of(309, 'Electrike')
  public static Manectric = EnumSpecies.of(310, 'Manectric')
  public static Plusle = EnumSpecies.of(311, 'Plusle')
  public static Minun = EnumSpecies.of(312, 'Minun')
  public static Volbeat = EnumSpecies.of(313, 'Volbeat')
  public static Illumise = EnumSpecies.of(314, 'Illumise')
  public static Roselia = EnumSpecies.of(315, 'Roselia')
  public static Gulpin = EnumSpecies.of(316, 'Gulpin')
  public static Swalot = EnumSpecies.of(317, 'Swalot')
  public static Carvanha = EnumSpecies.of(318, 'Carvanha')
  public static Sharpedo = EnumSpecies.of(319, 'Sharpedo')
  public static Wailmer = EnumSpecies.of(320, 'Wailmer')
  public static Wailord = EnumSpecies.of(321, 'Wailord')
  public static Numel = EnumSpecies.of(322, 'Numel')
  public static Camerupt = EnumSpecies.of(323, 'Camerupt')
  public static Torkoal = EnumSpecies.of(324, 'Torkoal')
  public static Spoink = EnumSpecies.of(325, 'Spoink')
  public static Grumpig = EnumSpecies.of(326, 'Grumpig')
  public static Spinda = EnumSpecies.of(327, 'Spinda')
  public static Trapinch = EnumSpecies.of(328, 'Trapinch')
  public static Vibrava = EnumSpecies.of(329, 'Vibrava')
  public static Flygon = EnumSpecies.of(330, 'Flygon')
  public static Cacnea = EnumSpecies.of(331, 'Cacnea')
  public static Cacturne = EnumSpecies.of(332, 'Cacturne')
  public static Swablu = EnumSpecies.of(333, 'Swablu')
  public static Altaria = EnumSpecies.of(334, 'Altaria')
  public static Zangoose = EnumSpecies.of(335, 'Zangoose')
  public static Seviper = EnumSpecies.of(336, 'Seviper')
  public static Lunatone = EnumSpecies.of(337, 'Lunatone')
  public static Solrock = EnumSpecies.of(338, 'Solrock')
  public static Barboach = EnumSpecies.of(339, 'Barboach')
  public static Whiscash = EnumSpecies.of(340, 'Whiscash')
  public static Corphish = EnumSpecies.of(341, 'Corphish')
  public static Crawdaunt = EnumSpecies.of(342, 'Crawdaunt')
  public static Baltoy = EnumSpecies.of(343, 'Baltoy')
  public static Claydol = EnumSpecies.of(344, 'Claydol')
  public static Lileep = EnumSpecies.of(345, 'Lileep')
  public static Cradily = EnumSpecies.of(346, 'Cradily')
  public static Anorith = EnumSpecies.of(347, 'Anorith')
  public static Armaldo = EnumSpecies.of(348, 'Armaldo')
  public static Feebas = EnumSpecies.of(349, 'Feebas')
  public static Milotic = EnumSpecies.of(350, 'Milotic')
  public static Castform = EnumSpecies.of(351, 'Castform')
  public static Kecleon = EnumSpecies.of(352, 'Kecleon')
  public static Shuppet = EnumSpecies.of(353, 'Shuppet')
  public static Banette = EnumSpecies.of(354, 'Banette')
  public static Duskull = EnumSpecies.of(355, 'Duskull')
  public static Dusclops = EnumSpecies.of(356, 'Dusclops')
  public static Tropius = EnumSpecies.of(357, 'Tropius')
  public static Chimecho = EnumSpecies.of(358, 'Chimecho')
  public static Absol = EnumSpecies.of(359, 'Absol')
  public static Wynaut = EnumSpecies.of(360, 'Wynaut')
  public static Snorunt = EnumSpecies.of(361, 'Snorunt')
  public static Glalie = EnumSpecies.of(362, 'Glalie')
  public static Spheal = EnumSpecies.of(363, 'Spheal')
  public static Sealeo = EnumSpecies.of(364, 'Sealeo')
  public static Walrein = EnumSpecies.of(365, 'Walrein')
  public static Clamperl = EnumSpecies.of(366, 'Clamperl')
  public static Huntail = EnumSpecies.of(367, 'Huntail')
  public static Gorebyss = EnumSpecies.of(368, 'Gorebyss')
  public static Relicanth = EnumSpecies.of(369, 'Relicanth')
  public static Luvdisc = EnumSpecies.of(370, 'Luvdisc')
  public static Bagon = EnumSpecies.of(371, 'Bagon')
  public static Shelgon = EnumSpecies.of(372, 'Shelgon')
  public static Salamence = EnumSpecies.of(373, 'Salamence')
  public static Beldum = EnumSpecies.of(374, 'Beldum')
  public static Metang = EnumSpecies.of(375, 'Metang')
  public static Metagross = EnumSpecies.of(376, 'Metagross')
  public static Regirock = EnumSpecies.of(377, 'Regirock')
  public static Regice = EnumSpecies.of(378, 'Regice')
  public static Registeel = EnumSpecies.of(379, 'Registeel')
  public static Latias = EnumSpecies.of(380, 'Latias')
  public static Latios = EnumSpecies.of(381, 'Latios')
  public static Kyogre = EnumSpecies.of(382, 'Kyogre')
  public static Groudon = EnumSpecies.of(383, 'Groudon')
  public static Rayquaza = EnumSpecies.of(384, 'Rayquaza')
  public static Jirachi = EnumSpecies.of(385, 'Jirachi')
  public static Deoxys = EnumSpecies.of(386, 'Deoxys')
  public static Turtwig = EnumSpecies.of(387, 'Turtwig')
  public static Grotle = EnumSpecies.of(388, 'Grotle')
  public static Torterra = EnumSpecies.of(389, 'Torterra')
  public static Chimchar = EnumSpecies.of(390, 'Chimchar')
  public static Monferno = EnumSpecies.of(391, 'Monferno')
  public static Infernape = EnumSpecies.of(392, 'Infernape')
  public static Piplup = EnumSpecies.of(393, 'Piplup')
  public static Prinplup = EnumSpecies.of(394, 'Prinplup')
  public static Empoleon = EnumSpecies.of(395, 'Empoleon')
  public static Starly = EnumSpecies.of(396, 'Starly')
  public static Staravia = EnumSpecies.of(397, 'Staravia')
  public static Staraptor = EnumSpecies.of(398, 'Staraptor')
  public static Bidoof = EnumSpecies.of(399, 'Bidoof')
  public static Bibarel = EnumSpecies.of(400, 'Bibarel')
  public static Kricketot = EnumSpecies.of(401, 'Kricketot')
  public static Kricketune = EnumSpecies.of(402, 'Kricketune')
  public static Shinx = EnumSpecies.of(403, 'Shinx')
  public static Luxio = EnumSpecies.of(404, 'Luxio')
  public static Luxray = EnumSpecies.of(405, 'Luxray')
  public static Budew = EnumSpecies.of(406, 'Budew')
  public static Roserade = EnumSpecies.of(407, 'Roserade')
  public static Cranidos = EnumSpecies.of(408, 'Cranidos')
  public static Rampardos = EnumSpecies.of(409, 'Rampardos')
  public static Shieldon = EnumSpecies.of(410, 'Shieldon')
  public static Bastiodon = EnumSpecies.of(411, 'Bastiodon')
  public static Burmy = EnumSpecies.of(412, 'Burmy')
  public static Wormadam = EnumSpecies.of(413, 'Wormadam')
  public static Mothim = EnumSpecies.of(414, 'Mothim')
  public static Combee = EnumSpecies.of(415, 'Combee')
  public static Vespiquen = EnumSpecies.of(416, 'Vespiquen')
  public static Pachirisu = EnumSpecies.of(417, 'Pachirisu')
  public static Buizel = EnumSpecies.of(418, 'Buizel')
  public static Floatzel = EnumSpecies.of(419, 'Floatzel')
  public static Cherubi = EnumSpecies.of(420, 'Cherubi')
  public static Cherrim = EnumSpecies.of(421, 'Cherrim')
  public static Shellos = EnumSpecies.of(422, 'Shellos')
  public static Gastrodon = EnumSpecies.of(423, 'Gastrodon')
  public static Ambipom = EnumSpecies.of(424, 'Ambipom')
  public static Drifloon = EnumSpecies.of(425, 'Drifloon')
  public static Drifblim = EnumSpecies.of(426, 'Drifblim')
  public static Buneary = EnumSpecies.of(427, 'Buneary')
  public static Lopunny = EnumSpecies.of(428, 'Lopunny')
  public static Mismagius = EnumSpecies.of(429, 'Mismagius')
  public static Honchkrow = EnumSpecies.of(430, 'Honchkrow')
  public static Glameow = EnumSpecies.of(431, 'Glameow')
  public static Purugly = EnumSpecies.of(432, 'Purugly')
  public static Chingling = EnumSpecies.of(433, 'Chingling')
  public static Stunky = EnumSpecies.of(434, 'Stunky')
  public static Skuntank = EnumSpecies.of(435, 'Skuntank')
  public static Bronzor = EnumSpecies.of(436, 'Bronzor')
  public static Bronzong = EnumSpecies.of(437, 'Bronzong')
  public static Bonsly = EnumSpecies.of(438, 'Bonsly')
  public static MimeJr = EnumSpecies.of(439, 'MimeJr')
  public static Happiny = EnumSpecies.of(440, 'Happiny')
  public static Chatot = EnumSpecies.of(441, 'Chatot')
  public static Spiritomb = EnumSpecies.of(442, 'Spiritomb')
  public static Gible = EnumSpecies.of(443, 'Gible')
  public static Gabite = EnumSpecies.of(444, 'Gabite')
  public static Garchomp = EnumSpecies.of(445, 'Garchomp')
  public static Munchlax = EnumSpecies.of(446, 'Munchlax')
  public static Riolu = EnumSpecies.of(447, 'Riolu')
  public static Lucario = EnumSpecies.of(448, 'Lucario')
  public static Hippopotas = EnumSpecies.of(449, 'Hippopotas')
  public static Hippowdon = EnumSpecies.of(450, 'Hippowdon')
  public static Skorupi = EnumSpecies.of(451, 'Skorupi')
  public static Drapion = EnumSpecies.of(452, 'Drapion')
  public static Croagunk = EnumSpecies.of(453, 'Croagunk')
  public static Toxicroak = EnumSpecies.of(454, 'Toxicroak')
  public static Carnivine = EnumSpecies.of(455, 'Carnivine')
  public static Finneon = EnumSpecies.of(456, 'Finneon')
  public static Lumineon = EnumSpecies.of(457, 'Lumineon')
  public static Mantyke = EnumSpecies.of(458, 'Mantyke')
  public static Snover = EnumSpecies.of(459, 'Snover')
  public static Abomasnow = EnumSpecies.of(460, 'Abomasnow')
  public static Weavile = EnumSpecies.of(461, 'Weavile')
  public static Magnezone = EnumSpecies.of(462, 'Magnezone')
  public static Lickilicky = EnumSpecies.of(463, 'Lickilicky')
  public static Rhyperior = EnumSpecies.of(464, 'Rhyperior')
  public static Tangrowth = EnumSpecies.of(465, 'Tangrowth')
  public static Electivire = EnumSpecies.of(466, 'Electivire')
  public static Magmortar = EnumSpecies.of(467, 'Magmortar')
  public static Togekiss = EnumSpecies.of(468, 'Togekiss')
  public static Yanmega = EnumSpecies.of(469, 'Yanmega')
  public static Leafeon = EnumSpecies.of(470, 'Leafeon')
  public static Glaceon = EnumSpecies.of(471, 'Glaceon')
  public static Gliscor = EnumSpecies.of(472, 'Gliscor')
  public static Mamoswine = EnumSpecies.of(473, 'Mamoswine')
  public static PorygonZ = EnumSpecies.of(474, 'Porygon-Z')
  public static Gallade = EnumSpecies.of(475, 'Gallade')
  public static Probopass = EnumSpecies.of(476, 'Probopass')
  public static Dusknoir = EnumSpecies.of(477, 'Dusknoir')
  public static Froslass = EnumSpecies.of(478, 'Froslass')
  public static Rotom = EnumSpecies.of(479, 'Rotom')
  public static Uxie = EnumSpecies.of(480, 'Uxie')
  public static Mesprit = EnumSpecies.of(481, 'Mesprit')
  public static Azelf = EnumSpecies.of(482, 'Azelf')
  public static Dialga = EnumSpecies.of(483, 'Dialga')
  public static Palkia = EnumSpecies.of(484, 'Palkia')
  public static Heatran = EnumSpecies.of(485, 'Heatran')
  public static Regigigas = EnumSpecies.of(486, 'Regigigas')
  public static Giratina = EnumSpecies.of(487, 'Giratina')
  public static Cresselia = EnumSpecies.of(488, 'Cresselia')
  public static Phione = EnumSpecies.of(489, 'Phione')
  public static Manaphy = EnumSpecies.of(490, 'Manaphy')
  public static Darkrai = EnumSpecies.of(491, 'Darkrai')
  public static Shaymin = EnumSpecies.of(492, 'Shaymin')
  public static Arceus = EnumSpecies.of(493, 'Arceus')
  public static Victini = EnumSpecies.of(494, 'Victini')
  public static Snivy = EnumSpecies.of(495, 'Snivy')
  public static Servine = EnumSpecies.of(496, 'Servine')
  public static Serperior = EnumSpecies.of(497, 'Serperior')
  public static Tepig = EnumSpecies.of(498, 'Tepig')
  public static Pignite = EnumSpecies.of(499, 'Pignite')
  public static Emboar = EnumSpecies.of(500, 'Emboar')
  public static Oshawott = EnumSpecies.of(501, 'Oshawott')
  public static Dewott = EnumSpecies.of(502, 'Dewott')
  public static Samurott = EnumSpecies.of(503, 'Samurott')
  public static Patrat = EnumSpecies.of(504, 'Patrat')
  public static Watchog = EnumSpecies.of(505, 'Watchog')
  public static Lillipup = EnumSpecies.of(506, 'Lillipup')
  public static Herdier = EnumSpecies.of(507, 'Herdier')
  public static Stoutland = EnumSpecies.of(508, 'Stoutland')
  public static Purrloin = EnumSpecies.of(509, 'Purrloin')
  public static Liepard = EnumSpecies.of(510, 'Liepard')
  public static Pansage = EnumSpecies.of(511, 'Pansage')
  public static Simisage = EnumSpecies.of(512, 'Simisage')
  public static Pansear = EnumSpecies.of(513, 'Pansear')
  public static Simisear = EnumSpecies.of(514, 'Simisear')
  public static Panpour = EnumSpecies.of(515, 'Panpour')
  public static Simipour = EnumSpecies.of(516, 'Simipour')
  public static Munna = EnumSpecies.of(517, 'Munna')
  public static Musharna = EnumSpecies.of(518, 'Musharna')
  public static Pidove = EnumSpecies.of(519, 'Pidove')
  public static Tranquill = EnumSpecies.of(520, 'Tranquill')
  public static Unfezant = EnumSpecies.of(521, 'Unfezant')
  public static Blitzle = EnumSpecies.of(522, 'Blitzle')
  public static Zebstrika = EnumSpecies.of(523, 'Zebstrika')
  public static Roggenrola = EnumSpecies.of(524, 'Roggenrola')
  public static Boldore = EnumSpecies.of(525, 'Boldore')
  public static Gigalith = EnumSpecies.of(526, 'Gigalith')
  public static Woobat = EnumSpecies.of(527, 'Woobat')
  public static Swoobat = EnumSpecies.of(528, 'Swoobat')
  public static Drilbur = EnumSpecies.of(529, 'Drilbur')
  public static Excadrill = EnumSpecies.of(530, 'Excadrill')
  public static Audino = EnumSpecies.of(531, 'Audino')
  public static Timburr = EnumSpecies.of(532, 'Timburr')
  public static Gurdurr = EnumSpecies.of(533, 'Gurdurr')
  public static Conkeldurr = EnumSpecies.of(534, 'Conkeldurr')
  public static Tympole = EnumSpecies.of(535, 'Tympole')
  public static Palpitoad = EnumSpecies.of(536, 'Palpitoad')
  public static Seismitoad = EnumSpecies.of(537, 'Seismitoad')
  public static Throh = EnumSpecies.of(538, 'Throh')
  public static Sawk = EnumSpecies.of(539, 'Sawk')
  public static Sewaddle = EnumSpecies.of(540, 'Sewaddle')
  public static Swadloon = EnumSpecies.of(541, 'Swadloon')
  public static Leavanny = EnumSpecies.of(542, 'Leavanny')
  public static Venipede = EnumSpecies.of(543, 'Venipede')
  public static Whirlipede = EnumSpecies.of(544, 'Whirlipede')
  public static Scolipede = EnumSpecies.of(545, 'Scolipede')
  public static Cottonee = EnumSpecies.of(546, 'Cottonee')
  public static Whimsicott = EnumSpecies.of(547, 'Whimsicott')
  public static Petilil = EnumSpecies.of(548, 'Petilil')
  public static Lilligant = EnumSpecies.of(549, 'Lilligant')
  public static Basculin = EnumSpecies.of(550, 'Basculin')
  public static Sandile = EnumSpecies.of(551, 'Sandile')
  public static Krokorok = EnumSpecies.of(552, 'Krokorok')
  public static Krookodile = EnumSpecies.of(553, 'Krookodile')
  public static Darumaka = EnumSpecies.of(554, 'Darumaka')
  public static Darmanitan = EnumSpecies.of(555, 'Darmanitan')
  public static Maractus = EnumSpecies.of(556, 'Maractus')
  public static Dwebble = EnumSpecies.of(557, 'Dwebble')
  public static Crustle = EnumSpecies.of(558, 'Crustle')
  public static Scraggy = EnumSpecies.of(559, 'Scraggy')
  public static Scrafty = EnumSpecies.of(560, 'Scrafty')
  public static Sigilyph = EnumSpecies.of(561, 'Sigilyph')
  public static Yamask = EnumSpecies.of(562, 'Yamask')
  public static Cofagrigus = EnumSpecies.of(563, 'Cofagrigus')
  public static Tirtouga = EnumSpecies.of(564, 'Tirtouga')
  public static Carracosta = EnumSpecies.of(565, 'Carracosta')
  public static Archen = EnumSpecies.of(566, 'Archen')
  public static Archeops = EnumSpecies.of(567, 'Archeops')
  public static Trubbish = EnumSpecies.of(568, 'Trubbish')
  public static Garbodor = EnumSpecies.of(569, 'Garbodor')
  public static Zorua = EnumSpecies.of(570, 'Zorua')
  public static Zoroark = EnumSpecies.of(571, 'Zoroark')
  public static Minccino = EnumSpecies.of(572, 'Minccino')
  public static Cinccino = EnumSpecies.of(573, 'Cinccino')
  public static Gothita = EnumSpecies.of(574, 'Gothita')
  public static Gothorita = EnumSpecies.of(575, 'Gothorita')
  public static Gothitelle = EnumSpecies.of(576, 'Gothitelle')
  public static Solosis = EnumSpecies.of(577, 'Solosis')
  public static Duosion = EnumSpecies.of(578, 'Duosion')
  public static Reuniclus = EnumSpecies.of(579, 'Reuniclus')
  public static Ducklett = EnumSpecies.of(580, 'Ducklett')
  public static Swanna = EnumSpecies.of(581, 'Swanna')
  public static Vanillite = EnumSpecies.of(582, 'Vanillite')
  public static Vanillish = EnumSpecies.of(583, 'Vanillish')
  public static Vanilluxe = EnumSpecies.of(584, 'Vanilluxe')
  public static Deerling = EnumSpecies.of(585, 'Deerling')
  public static Sawsbuck = EnumSpecies.of(586, 'Sawsbuck')
  public static Emolga = EnumSpecies.of(587, 'Emolga')
  public static Karrablast = EnumSpecies.of(588, 'Karrablast')
  public static Escavalier = EnumSpecies.of(589, 'Escavalier')
  public static Foongus = EnumSpecies.of(590, 'Foongus')
  public static Amoonguss = EnumSpecies.of(591, 'Amoonguss')
  public static Frillish = EnumSpecies.of(592, 'Frillish')
  public static Jellicent = EnumSpecies.of(593, 'Jellicent')
  public static Alomomola = EnumSpecies.of(594, 'Alomomola')
  public static Joltik = EnumSpecies.of(595, 'Joltik')
  public static Galvantula = EnumSpecies.of(596, 'Galvantula')
  public static Ferroseed = EnumSpecies.of(597, 'Ferroseed')
  public static Ferrothorn = EnumSpecies.of(598, 'Ferrothorn')
  public static Klink = EnumSpecies.of(599, 'Klink')
  public static Klang = EnumSpecies.of(600, 'Klang')
  public static Klinklang = EnumSpecies.of(601, 'Klinklang')
  public static Tynamo = EnumSpecies.of(602, 'Tynamo')
  public static Eelektrik = EnumSpecies.of(603, 'Eelektrik')
  public static Eelektross = EnumSpecies.of(604, 'Eelektross')
  public static Elgyem = EnumSpecies.of(605, 'Elgyem')
  public static Beheeyem = EnumSpecies.of(606, 'Beheeyem')
  public static Litwick = EnumSpecies.of(607, 'Litwick')
  public static Lampent = EnumSpecies.of(608, 'Lampent')
  public static Chandelure = EnumSpecies.of(609, 'Chandelure')
  public static Axew = EnumSpecies.of(610, 'Axew')
  public static Fraxure = EnumSpecies.of(611, 'Fraxure')
  public static Haxorus = EnumSpecies.of(612, 'Haxorus')
  public static Cubchoo = EnumSpecies.of(613, 'Cubchoo')
  public static Beartic = EnumSpecies.of(614, 'Beartic')
  public static Cryogonal = EnumSpecies.of(615, 'Cryogonal')
  public static Shelmet = EnumSpecies.of(616, 'Shelmet')
  public static Accelgor = EnumSpecies.of(617, 'Accelgor')
  public static Stunfisk = EnumSpecies.of(618, 'Stunfisk')
  public static Mienfoo = EnumSpecies.of(619, 'Mienfoo')
  public static Mienshao = EnumSpecies.of(620, 'Mienshao')
  public static Druddigon = EnumSpecies.of(621, 'Druddigon')
  public static Golett = EnumSpecies.of(622, 'Golett')
  public static Golurk = EnumSpecies.of(623, 'Golurk')
  public static Pawniard = EnumSpecies.of(624, 'Pawniard')
  public static Bisharp = EnumSpecies.of(625, 'Bisharp')
  public static Bouffalant = EnumSpecies.of(626, 'Bouffalant')
  public static Rufflet = EnumSpecies.of(627, 'Rufflet')
  public static Braviary = EnumSpecies.of(628, 'Braviary')
  public static Vullaby = EnumSpecies.of(629, 'Vullaby')
  public static Mandibuzz = EnumSpecies.of(630, 'Mandibuzz')
  public static Heatmor = EnumSpecies.of(631, 'Heatmor')
  public static Durant = EnumSpecies.of(632, 'Durant')
  public static Deino = EnumSpecies.of(633, 'Deino')
  public static Zweilous = EnumSpecies.of(634, 'Zweilous')
  public static Hydreigon = EnumSpecies.of(635, 'Hydreigon')
  public static Larvesta = EnumSpecies.of(636, 'Larvesta')
  public static Volcarona = EnumSpecies.of(637, 'Volcarona')
  public static Cobalion = EnumSpecies.of(638, 'Cobalion')
  public static Terrakion = EnumSpecies.of(639, 'Terrakion')
  public static Virizion = EnumSpecies.of(640, 'Virizion')
  public static Tornadus = EnumSpecies.of(641, 'Tornadus')
  public static Thundurus = EnumSpecies.of(642, 'Thundurus')
  public static Reshiram = EnumSpecies.of(643, 'Reshiram')
  public static Zekrom = EnumSpecies.of(644, 'Zekrom')
  public static Landorus = EnumSpecies.of(645, 'Landorus')
  public static Kyurem = EnumSpecies.of(646, 'Kyurem')
  public static Keldeo = EnumSpecies.of(647, 'Keldeo')
  public static Meloetta = EnumSpecies.of(648, 'Meloetta')
  public static Genesect = EnumSpecies.of(649, 'Genesect')
  public static Chespin = EnumSpecies.of(650, 'Chespin')
  public static Quilladin = EnumSpecies.of(651, 'Quilladin')
  public static Chesnaught = EnumSpecies.of(652, 'Chesnaught')
  public static Fennekin = EnumSpecies.of(653, 'Fennekin')
  public static Braixen = EnumSpecies.of(654, 'Braixen')
  public static Delphox = EnumSpecies.of(655, 'Delphox')
  public static Froakie = EnumSpecies.of(656, 'Froakie')
  public static Frogadier = EnumSpecies.of(657, 'Frogadier')
  public static Greninja = EnumSpecies.of(658, 'Greninja')
  public static Bunnelby = EnumSpecies.of(659, 'Bunnelby')
  public static Diggersby = EnumSpecies.of(660, 'Diggersby')
  public static Fletchling = EnumSpecies.of(661, 'Fletchling')
  public static Fletchinder = EnumSpecies.of(662, 'Fletchinder')
  public static Talonflame = EnumSpecies.of(663, 'Talonflame')
  public static Scatterbug = EnumSpecies.of(664, 'Scatterbug')
  public static Spewpa = EnumSpecies.of(665, 'Spewpa')
  public static Vivillon = EnumSpecies.of(666, 'Vivillon')
  public static Litleo = EnumSpecies.of(667, 'Litleo')
  public static Pyroar = EnumSpecies.of(668, 'Pyroar')
  public static Flabebe = EnumSpecies.of(669, 'Flabebe')
  public static Floette = EnumSpecies.of(670, 'Floette')
  public static Florges = EnumSpecies.of(671, 'Florges')
  public static Skiddo = EnumSpecies.of(672, 'Skiddo')
  public static Gogoat = EnumSpecies.of(673, 'Gogoat')
  public static Pancham = EnumSpecies.of(674, 'Pancham')
  public static Pangoro = EnumSpecies.of(675, 'Pangoro')
  public static Furfrou = EnumSpecies.of(676, 'Furfrou')
  public static Espurr = EnumSpecies.of(677, 'Espurr')
  public static Meowstic = EnumSpecies.of(678, 'Meowstic')
  public static Honedge = EnumSpecies.of(679, 'Honedge')
  public static Doublade = EnumSpecies.of(680, 'Doublade')
  public static Aegislash = EnumSpecies.of(681, 'Aegislash')
  public static Spritzee = EnumSpecies.of(682, 'Spritzee')
  public static Aromatisse = EnumSpecies.of(683, 'Aromatisse')
  public static Swirlix = EnumSpecies.of(684, 'Swirlix')
  public static Slurpuff = EnumSpecies.of(685, 'Slurpuff')
  public static Inkay = EnumSpecies.of(686, 'Inkay')
  public static Malamar = EnumSpecies.of(687, 'Malamar')
  public static Binacle = EnumSpecies.of(688, 'Binacle')
  public static Barbaracle = EnumSpecies.of(689, 'Barbaracle')
  public static Skrelp = EnumSpecies.of(690, 'Skrelp')
  public static Dragalge = EnumSpecies.of(691, 'Dragalge')
  public static Clauncher = EnumSpecies.of(692, 'Clauncher')
  public static Clawitzer = EnumSpecies.of(693, 'Clawitzer')
  public static Helioptile = EnumSpecies.of(694, 'Helioptile')
  public static Heliolisk = EnumSpecies.of(695, 'Heliolisk')
  public static Tyrunt = EnumSpecies.of(696, 'Tyrunt')
  public static Tyrantrum = EnumSpecies.of(697, 'Tyrantrum')
  public static Amaura = EnumSpecies.of(698, 'Amaura')
  public static Aurorus = EnumSpecies.of(699, 'Aurorus')
  public static Sylveon = EnumSpecies.of(700, 'Sylveon')
  public static Hawlucha = EnumSpecies.of(701, 'Hawlucha')
  public static Dedenne = EnumSpecies.of(702, 'Dedenne')
  public static Carbink = EnumSpecies.of(703, 'Carbink')
  public static Goomy = EnumSpecies.of(704, 'Goomy')
  public static Sliggoo = EnumSpecies.of(705, 'Sliggoo')
  public static Goodra = EnumSpecies.of(706, 'Goodra')
  public static Klefki = EnumSpecies.of(707, 'Klefki')
  public static Phantump = EnumSpecies.of(708, 'Phantump')
  public static Trevenant = EnumSpecies.of(709, 'Trevenant')
  public static Pumpkaboo = EnumSpecies.of(710, 'Pumpkaboo')
  public static Gourgeist = EnumSpecies.of(711, 'Gourgeist')
  public static Bergmite = EnumSpecies.of(712, 'Bergmite')
  public static Avalugg = EnumSpecies.of(713, 'Avalugg')
  public static Noibat = EnumSpecies.of(714, 'Noibat')
  public static Noivern = EnumSpecies.of(715, 'Noivern')
  public static Xerneas = EnumSpecies.of(716, 'Xerneas')
  public static Yveltal = EnumSpecies.of(717, 'Yveltal')
  public static Zygarde = EnumSpecies.of(718, 'Zygarde')
  public static Diancie = EnumSpecies.of(719, 'Diancie')
  public static Hoopa = EnumSpecies.of(720, 'Hoopa')
  public static Volcanion = EnumSpecies.of(721, 'Volcanion')
  public static Rowlet = EnumSpecies.of(722, 'Rowlet')
  public static Dartrix = EnumSpecies.of(723, 'Dartrix')
  public static Decidueye = EnumSpecies.of(724, 'Decidueye')
  public static Litten = EnumSpecies.of(725, 'Litten')
  public static Torracat = EnumSpecies.of(726, 'Torracat')
  public static Incineroar = EnumSpecies.of(727, 'Incineroar')
  public static Popplio = EnumSpecies.of(728, 'Popplio')
  public static Brionne = EnumSpecies.of(729, 'Brionne')
  public static Primarina = EnumSpecies.of(730, 'Primarina')
  public static Pikipek = EnumSpecies.of(731, 'Pikipek')
  public static Trumbeak = EnumSpecies.of(732, 'Trumbeak')
  public static Toucannon = EnumSpecies.of(733, 'Toucannon')
  public static Yungoos = EnumSpecies.of(734, 'Yungoos')
  public static Gumshoos = EnumSpecies.of(735, 'Gumshoos')
  public static Grubbin = EnumSpecies.of(736, 'Grubbin')
  public static Charjabug = EnumSpecies.of(737, 'Charjabug')
  public static Vikavolt = EnumSpecies.of(738, 'Vikavolt')
  public static Crabrawler = EnumSpecies.of(739, 'Crabrawler')
  public static Crabominable = EnumSpecies.of(740, 'Crabominable')
  public static Oricorio = EnumSpecies.of(741, 'Oricorio')
  public static Cutiefly = EnumSpecies.of(742, 'Cutiefly')
  public static Ribombee = EnumSpecies.of(743, 'Ribombee')
  public static Rockruff = EnumSpecies.of(744, 'Rockruff')
  public static Lycanroc = EnumSpecies.of(745, 'Lycanroc')
  public static Wishiwashi = EnumSpecies.of(746, 'Wishiwashi')
  public static Mareanie = EnumSpecies.of(747, 'Mareanie')
  public static Toxapex = EnumSpecies.of(748, 'Toxapex')
  public static Mudbray = EnumSpecies.of(749, 'Mudbray')
  public static Mudsdale = EnumSpecies.of(750, 'Mudsdale')
  public static Dewpider = EnumSpecies.of(751, 'Dewpider')
  public static Araquanid = EnumSpecies.of(752, 'Araquanid')
  public static Fomantis = EnumSpecies.of(753, 'Fomantis')
  public static Lurantis = EnumSpecies.of(754, 'Lurantis')
  public static Morelull = EnumSpecies.of(755, 'Morelull')
  public static Shiinotic = EnumSpecies.of(756, 'Shiinotic')
  public static Salandit = EnumSpecies.of(757, 'Salandit')
  public static Salazzle = EnumSpecies.of(758, 'Salazzle')
  public static Stufful = EnumSpecies.of(759, 'Stufful')
  public static Bewear = EnumSpecies.of(760, 'Bewear')
  public static Bounsweet = EnumSpecies.of(761, 'Bounsweet')
  public static Steenee = EnumSpecies.of(762, 'Steenee')
  public static Tsareena = EnumSpecies.of(763, 'Tsareena')
  public static Comfey = EnumSpecies.of(764, 'Comfey')
  public static Oranguru = EnumSpecies.of(765, 'Oranguru')
  public static Passimian = EnumSpecies.of(766, 'Passimian')
  public static Wimpod = EnumSpecies.of(767, 'Wimpod')
  public static Golisopod = EnumSpecies.of(768, 'Golisopod')
  public static Sandygast = EnumSpecies.of(769, 'Sandygast')
  public static Palossand = EnumSpecies.of(770, 'Palossand')
  public static Pyukumuku = EnumSpecies.of(771, 'Pyukumuku')
  public static TypeNull = EnumSpecies.of(772, 'TypeNull')
  public static Silvally = EnumSpecies.of(773, 'Silvally')
  public static Minior = EnumSpecies.of(774, 'Minior')
  public static Komala = EnumSpecies.of(775, 'Komala')
  public static Turtonator = EnumSpecies.of(776, 'Turtonator')
  public static Togedemaru = EnumSpecies.of(777, 'Togedemaru')
  public static Mimikyu = EnumSpecies.of(778, 'Mimikyu')
  public static Bruxish = EnumSpecies.of(779, 'Bruxish')
  public static Drampa = EnumSpecies.of(780, 'Drampa')
  public static Dhelmise = EnumSpecies.of(781, 'Dhelmise')
  public static Jangmoo = EnumSpecies.of(782, 'Jangmo-o')
  public static Hakamoo = EnumSpecies.of(783, 'Hakamo-o')
  public static Kommoo = EnumSpecies.of(784, 'Kommo-o')
  public static TapuKoko = EnumSpecies.of(785, 'TapuKoko')
  public static TapuLele = EnumSpecies.of(786, 'TapuLele')
  public static TapuBulu = EnumSpecies.of(787, 'TapuBulu')
  public static TapuFini = EnumSpecies.of(788, 'TapuFini')
  public static Cosmog = EnumSpecies.of(789, 'Cosmog')
  public static Cosmoem = EnumSpecies.of(790, 'Cosmoem')
  public static Solgaleo = EnumSpecies.of(791, 'Solgaleo')
  public static Lunala = EnumSpecies.of(792, 'Lunala')
  public static Nihilego = EnumSpecies.of(793, 'Nihilego')
  public static Buzzwole = EnumSpecies.of(794, 'Buzzwole')
  public static Pheromosa = EnumSpecies.of(795, 'Pheromosa')
  public static Xurkitree = EnumSpecies.of(796, 'Xurkitree')
  public static Celesteela = EnumSpecies.of(797, 'Celesteela')
  public static Kartana = EnumSpecies.of(798, 'Kartana')
  public static Guzzlord = EnumSpecies.of(799, 'Guzzlord')
  public static Necrozma = EnumSpecies.of(800, 'Necrozma')
  public static Magearna = EnumSpecies.of(801, 'Magearna')
  public static Marshadow = EnumSpecies.of(802, 'Marshadow')
  public static Poipole = EnumSpecies.of(803, 'Poipole')
  public static Naganadel = EnumSpecies.of(804, 'Naganadel')
  public static Stakataka = EnumSpecies.of(805, 'Stakataka')
  public static Blacephalon = EnumSpecies.of(806, 'Blacephalon')
  public static Zeraora = EnumSpecies.of(807, 'Zeraora')
  public static Meltan = EnumSpecies.of(808, 'Meltan')
  public static Melmetal = EnumSpecies.of(809, 'Melmetal')
  public static Grookey = EnumSpecies.of(810, 'Grookey')
  public static Thwackey = EnumSpecies.of(811, 'Thwackey')
  public static Rillaboom = EnumSpecies.of(812, 'Rillaboom')
  public static Scorbunny = EnumSpecies.of(813, 'Scorbunny')
  public static Raboot = EnumSpecies.of(814, 'Raboot')
  public static Cinderace = EnumSpecies.of(815, 'Cinderace')
  public static Sobble = EnumSpecies.of(816, 'Sobble')
  public static Drizzile = EnumSpecies.of(817, 'Drizzile')
  public static Inteleon = EnumSpecies.of(818, 'Inteleon')
  public static Skwovet = EnumSpecies.of(819, 'Skwovet')
  public static Greedent = EnumSpecies.of(820, 'Greedent')
  public static Rookidee = EnumSpecies.of(821, 'Rookidee')
  public static Corvisquire = EnumSpecies.of(822, 'Corvisquire')
  public static Corviknight = EnumSpecies.of(823, 'Corviknight')
  public static Blipbug = EnumSpecies.of(824, 'Blipbug')
  public static Dottler = EnumSpecies.of(825, 'Dottler')
  public static Orbeetle = EnumSpecies.of(826, 'Orbeetle')
  public static Nickit = EnumSpecies.of(827, 'Nickit')
  public static Thievul = EnumSpecies.of(828, 'Thievul')
  public static Gossifleur = EnumSpecies.of(829, 'Gossifleur')
  public static Eldegoss = EnumSpecies.of(830, 'Eldegoss')
  public static Wooloo = EnumSpecies.of(831, 'Wooloo')
  public static Dubwool = EnumSpecies.of(832, 'Dubwool')
  public static Chewtle = EnumSpecies.of(833, 'Chewtle')
  public static Drednaw = EnumSpecies.of(834, 'Drednaw')
  public static Yamper = EnumSpecies.of(835, 'Yamper')
  public static Boltund = EnumSpecies.of(836, 'Boltund')
  public static Rolycoly = EnumSpecies.of(837, 'Rolycoly')
  public static Carkol = EnumSpecies.of(838, 'Carkol')
  public static Coalossal = EnumSpecies.of(839, 'Coalossal')
  public static Applin = EnumSpecies.of(840, 'Applin')
  public static Flapple = EnumSpecies.of(841, 'Flapple')
  public static Appletun = EnumSpecies.of(842, 'Appletun')
  public static Silicobra = EnumSpecies.of(843, 'Silicobra')
  public static Sandaconda = EnumSpecies.of(844, 'Sandaconda')
  public static Cramorant = EnumSpecies.of(845, 'Cramorant')
  public static Arrokuda = EnumSpecies.of(846, 'Arrokuda')
  public static Barraskewda = EnumSpecies.of(847, 'Barraskewda')
  public static Toxel = EnumSpecies.of(848, 'Toxel')
  public static Toxtricity = EnumSpecies.of(849, 'Toxtricity')
  public static Sizzlipede = EnumSpecies.of(850, 'Sizzlipede')
  public static Centiskorch = EnumSpecies.of(851, 'Centiskorch')
  public static Clobbopus = EnumSpecies.of(852, 'Clobbopus')
  public static Grapploct = EnumSpecies.of(853, 'Grapploct')
  public static Sinistea = EnumSpecies.of(854, 'Sinistea')
  public static Polteageist = EnumSpecies.of(855, 'Polteageist')
  public static Hatenna = EnumSpecies.of(856, 'Hatenna')
  public static Hattrem = EnumSpecies.of(857, 'Hattrem')
  public static Hatterene = EnumSpecies.of(858, 'Hatterene')
  public static Impidimp = EnumSpecies.of(859, 'Impidimp')
  public static Morgrem = EnumSpecies.of(860, 'Morgrem')
  public static Grimmsnarl = EnumSpecies.of(861, 'Grimmsnarl')
  public static Obstagoon = EnumSpecies.of(862, 'Obstagoon')
  public static Perrserker = EnumSpecies.of(863, 'Perrserker')
  public static Cursola = EnumSpecies.of(864, 'Cursola')
  public static Sirfetchd = EnumSpecies.of(865, 'Sirfetchd')
  public static MrRime = EnumSpecies.of(866, 'MrRime')
  public static Runerigus = EnumSpecies.of(867, 'Runerigus')
  public static Milcery = EnumSpecies.of(868, 'Milcery')
  public static Alcremie = EnumSpecies.of(869, 'Alcremie')
  public static Falinks = EnumSpecies.of(870, 'Falinks')
  public static Pincurchin = EnumSpecies.of(871, 'Pincurchin')
  public static Snom = EnumSpecies.of(872, 'Snom')
  public static Frosmoth = EnumSpecies.of(873, 'Frosmoth')
  public static Stonjourner = EnumSpecies.of(874, 'Stonjourner')
  public static Eiscue = EnumSpecies.of(875, 'Eiscue')
  public static Indeedee = EnumSpecies.of(876, 'Indeedee')
  public static Morpeko = EnumSpecies.of(877, 'Morpeko')
  public static Cufant = EnumSpecies.of(878, 'Cufant')
  public static Copperajah = EnumSpecies.of(879, 'Copperajah')
  public static Dracozolt = EnumSpecies.of(880, 'Dracozolt')
  public static Arctozolt = EnumSpecies.of(881, 'Arctozolt')
  public static Dracovish = EnumSpecies.of(882, 'Dracovish')
  public static Arctovish = EnumSpecies.of(883, 'Arctovish')
  public static Duraludon = EnumSpecies.of(884, 'Duraludon')
  public static Dreepy = EnumSpecies.of(885, 'Dreepy')
  public static Drakloak = EnumSpecies.of(886, 'Drakloak')
  public static Dragapult = EnumSpecies.of(887, 'Dragapult')
  public static Zacian = EnumSpecies.of(888, 'Zacian')
  public static Zamazenta = EnumSpecies.of(889, 'Zamazenta')
  public static Eternatus = EnumSpecies.of(890, 'Eternatus')
  public static Kubfu = EnumSpecies.of(891, 'Kubfu')
  public static Urshifu = EnumSpecies.of(892, 'Urshifu')
  public static Zarude = EnumSpecies.of(893, 'Zarude')
  public static Regieleki = EnumSpecies.of(894, 'Regieleki')
  public static Regidrago = EnumSpecies.of(895, 'Regidrago')
  public static Glastrier = EnumSpecies.of(896, 'Glastrier')
  public static Spectrier = EnumSpecies.of(897, 'Spectrier')
  public static Calyrex = EnumSpecies.of(898, 'Calyrex')

  public static legendaries = [
    EnumSpecies.MissingNo,
    /** Gen1 */
    EnumSpecies.Articuno,
    EnumSpecies.Zapdos,
    EnumSpecies.Moltres,
    EnumSpecies.Mewtwo,
    EnumSpecies.Mew,
    /** Gen2 */
    EnumSpecies.Raikou,
    EnumSpecies.Entei,
    EnumSpecies.Suicune,
    EnumSpecies.Lugia,
    EnumSpecies.Hooh,
    EnumSpecies.Celebi,
    /** Gen3 */
    EnumSpecies.Regirock,
    EnumSpecies.Regice,
    EnumSpecies.Registeel,
    EnumSpecies.Latias,
    EnumSpecies.Latios,
    EnumSpecies.Kyogre,
    EnumSpecies.Groudon,
    EnumSpecies.Rayquaza,
    EnumSpecies.Jirachi,
    /** Gen4 */
    EnumSpecies.Uxie,
    EnumSpecies.Mesprit,
    EnumSpecies.Azelf,
    EnumSpecies.Dialga,
    EnumSpecies.Palkia,
    EnumSpecies.Heatran,
    EnumSpecies.Regigigas,
    EnumSpecies.Giratina,
    /** Gen5 */
    EnumSpecies.Cobalion,
    EnumSpecies.Terrakion,
    EnumSpecies.Virizion,
    EnumSpecies.Tornadus,
    EnumSpecies.Thundurus,
    EnumSpecies.Landorus,
    /** Gen6 */
    EnumSpecies.Xerneas,
    EnumSpecies.Yveltal,
    EnumSpecies.Zygarde,
    EnumSpecies.Diancie,
    EnumSpecies.Hoopa,
    EnumSpecies.Volcanion,
    /** Gen7 */
    EnumSpecies.TypeNull,
    EnumSpecies.Silvally,
    EnumSpecies.TapuKoko,
    EnumSpecies.TapuLele,
    EnumSpecies.TapuBulu,
    EnumSpecies.TapuFini,
    EnumSpecies.Cosmog,
    EnumSpecies.Cosmoem,
    EnumSpecies.Solgaleo,
    EnumSpecies.Lunala,
    EnumSpecies.Necrozma,
    EnumSpecies.Marshadow,
    EnumSpecies.Magearna,
    EnumSpecies.Zeraora,
    EnumSpecies.Meltan,
    EnumSpecies.Melmetal,
    /** Gen8 */
    EnumSpecies.Zacian,
    EnumSpecies.Zamazenta,
    EnumSpecies.Eternatus,
    EnumSpecies.Kubfu,
    EnumSpecies.Urshifu,
    EnumSpecies.Zarude,
    EnumSpecies.Regieleki,
    EnumSpecies.Regidrago,
    EnumSpecies.Glastrier,
    EnumSpecies.Spectrier,
    EnumSpecies.Calyrex
  ]

  private constructor(
    private readonly nationalDex: number,
    private readonly name: string
  ) {
    const PokemonSet = EnumSpecies.PokemonSet as Set<EnumSpecies>
    PokemonSet.add(this)
  }

  public static hasPokemon(name: string): boolean {
    if (EnumSpecies.getFromName(name)) return true
    return false
  }

  public static getFromName(name: string): EnumSpecies | null {
    for (const pokemon of EnumSpecies.PokemonSet) {
      if (
        pokemon.name.toLowerCase() === name.toLowerCase() ||
        pokemon.getLocalizedName() === name.toLowerCase()
      )
        return pokemon
    }

    return null
  }

  private static of(dex: number, name: string): EnumSpecies {
    return new EnumSpecies(dex, name)
  }

  public isLegendary(): boolean {
    return EnumSpecies.legendaries.some(legendary => legendary === this)
  }

  public getName(): string {
    return this.name
  }

  public getLocalizedName(): string {
    return i18next.t(`Pixelmon:${this.name.toLowerCase()}.name`)
  }

  public getNationalPokedexNumber(): string {
    return String(this.nationalDex).padStart(3, '0')
  }

  public getNationalPokedexInteger(): number {
    return this.nationalDex
  }

  public toString(): string {
    return `EnumSpecies<${this.name}>`
  }
}
