export const enum Type {
  Normal = `Normal`,
  Fire = `Fire`,
  Water = `Water`,
  Electric = `Electric`,
  Grass = `Grass`,
  Ice = `Ice`,
  Fighting = `Fighting`,
  Poison = `Poison`,
  Ground = `Ground`,
  Flying = `Flying`,
  Psychic = `Psychic`,
  Bug = `Bug`,
  Rock = `Rock`,
  Ghost = `Ghost`,
  Dragon = `Dragon`,
  Dark = `Dark`,
  Steel = `Steel`,
  Fairy = `Fairy`,
  Shiny = `Shiny`,
  ha = `ha`
}
